package com.bpms.model;

// Generated 2015-6-16 10:13:19 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TSysParameter generated by hbm2java
 */
@Entity
@Table(name = "t_sys_parameter")
public class SysParameter implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer pramId;
	private String parmCode;
	private String parmName;
	private String parmValue;
	private char status;
	private Date createDate;
	private String creator;
	private Date updateDate;
	private String updater;
	private String description;

	public SysParameter() {
	}

	public SysParameter(Integer pramId, String parmCode, String parmName,
			String parmValue, char status) {
		this.pramId = pramId;
		this.parmCode = parmCode;
		this.parmName = parmName;
		this.parmValue = parmValue;
		this.status = status;
	}

	public SysParameter(Integer pramId, String parmCode, String parmName,
			String parmValue, char status, Date createDate, String creator,
			Date updateDate, String updater, String description) {
		this.pramId = pramId;
		this.parmCode = parmCode;
		this.parmName = parmName;
		this.parmValue = parmValue;
		this.status = status;
		this.createDate = createDate;
		this.creator = creator;
		this.updateDate = updateDate;
		this.updater = updater;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@GenericGenerator(name = "paymentableGenerator", strategy = "native")
	@Column(name = "PRAM_ID", insertable = true, updatable = true, nullable = false, length = 40, unique = true)
	public Integer getPramId() {
		return this.pramId;
	}

	public void setPramId(Integer pramId) {
		this.pramId = pramId;
	}

	@Column(name = "PARM_CODE", nullable = false, length = 50)
	public String getParmCode() {
		return this.parmCode;
	}

	public void setParmCode(String parmCode) {
		this.parmCode = parmCode;
	}

	@Column(name = "PARM_NAME", nullable = false, length = 100)
	public String getParmName() {
		return this.parmName;
	}

	public void setParmName(String parmName) {
		this.parmName = parmName;
	}

	@Column(name = "PARM_VALUE", nullable = false, length = 100)
	public String getParmValue() {
		return this.parmValue;
	}

	public void setParmValue(String parmValue) {
		this.parmValue = parmValue;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATOR", length = 40)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "UPDATER", length = 40)
	public String getUpdater() {
		return this.updater;
	}

	public void setUpdater(String updater) {
		this.updater = updater;
	}

	@Column(name = "DESCRIPTION", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
