package com.oasys.model;

// Generated 2015-10-26 10:38:26 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.springframework.format.annotation.DateTimeFormat;

import com.oasys.viewModel.WorkFlowTasksModel;

/**
 * TOaHrEmpDimissionApp generated by hbm2java
 */
@Entity
@Table(name = "t_oa_hr_emp_dimission_app", uniqueConstraints = @UniqueConstraint(columnNames = "APP_NO"))
public class EmpDimissionApp implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer edaId;
	private String appNo;
	private Date appDate;
	private Integer applicantNo;
	private String account;
	
	private Character gender;
	private String familyAddr;
	private Integer deptNo;
	private String deptName;
	private String mobile;
	private String position;
	private Date entryDate;
	private Date dimissionDate;
	private String dimissionReson;
	private String propose;
	private String remark;
	private String appStatus;
	private String procStatus;
	private String appDateBefore;//查询申请时间开始绑定字段
	private String appDateAfter;//查询申请时间结束绑定字段
	private WorkFlowTasksModel taskModel;//task对象
	private String result;//审批通过或驳回标识
	private String taskID;//任务taskID
	private String formKey;//跳转对应的受理页面JSP配置(在流程图的formKey中设置)
	private String assistant;//指定的候选人
	private String isSuccess;//是否通过标识
	private String resourcesName;//资源文件名称
	private String definitionKey;//流程标识Key
	private String formKeyJson;
	public EmpDimissionApp() {
	}

	public EmpDimissionApp(String appNo, Date appDate,
			Integer applicantNo, Character gender, String familyAddr,
			Integer deptNo, String deptName, String mobile, String position,
			Date entryDate, Date dimissionDate, String dimissionReson,
			String propose, String remark,String appStatus,String procStatus,String formKeyJson) {
		this.appNo = appNo;
		this.appDate = appDate;
		this.applicantNo = applicantNo;
		this.gender = gender;
		this.familyAddr = familyAddr;
		this.deptNo = deptNo;
		this.deptName = deptName;
		this.mobile = mobile;
		this.position = position;
		this.entryDate = entryDate;
		this.dimissionDate = dimissionDate;
		this.dimissionReson = dimissionReson;
		this.propose = propose;
		this.remark = remark;
		this.appStatus=appStatus;
		this.procStatus=procStatus;
		this.formKeyJson=formKeyJson;
	}
	@Transient
	public String getFormKeyJson() {
		return formKeyJson;
	}

	public void setFormKeyJson(String formKeyJson) {
		this.formKeyJson = formKeyJson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EDA_ID", unique = true, nullable = false)
	public Integer getEdaId() {
		return this.edaId;
	}

	public void setEdaId(Integer edaId) {
		this.edaId = edaId;
	}

	@Column(name = "APP_NO", unique = true, length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APP_DATE", length = 10)
	@DateTimeFormat(pattern="yyyy-MM-dd")
	public Date getAppDate() {
		return this.appDate;
	}

	public void setAppDate(Date appDate) {
		this.appDate = appDate;
	}

	@Column(name = "APPLICANT_NO")
	public Integer getApplicantNo() {
		return this.applicantNo;
	}

	public void setApplicantNo(Integer applicantNo) {
		this.applicantNo = applicantNo;
	}

	@Column(name = "GENDER", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "FAMILY_ADDR", length = 200)
	public String getFamilyAddr() {
		return this.familyAddr;
	}

	public void setFamilyAddr(String familyAddr) {
		this.familyAddr = familyAddr;
	}

	@Column(name = "DEPT_NO")
	public Integer getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(Integer deptNo) {
		this.deptNo = deptNo;
	}

	@Column(name = "DEPT_NAME", length = 50)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "MOBILE", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "POSITION", length = 50)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENTRY_DATE", length = 10)
	@DateTimeFormat(pattern="yyyy-MM-dd")
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DIMISSION_DATE", length = 10)
	@DateTimeFormat(pattern="yyyy-MM-dd")
	public Date getDimissionDate() {
		return this.dimissionDate;
	}

	public void setDimissionDate(Date dimissionDate) {
		this.dimissionDate = dimissionDate;
	}

	@Column(name = "DIMISSION_RESON", length = 250)
	public String getDimissionReson() {
		return this.dimissionReson;
	}

	public void setDimissionReson(String dimissionReson) {
		this.dimissionReson = dimissionReson;
	}

	@Column(name = "PROPOSE", length = 500)
	public String getPropose() {
		return this.propose;
	}

	public void setPropose(String propose) {
		this.propose = propose;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	@Column(name = "APP_STATUS", length = 100)
	public String getAppStatus() {
		return this.appStatus;
	}

	public void setAppStatus(String appStatus) {
		this.appStatus = appStatus;
	}

	@Column(name = "PROC_STATUS", length = 1)
	public String getProcStatus() {
		return this.procStatus;
	}

	public void setProcStatus(String procStatus) {
		this.procStatus = procStatus;
	}
	@Transient
	public String getAppDateBefore() {
		return appDateBefore;
	}

	public void setAppDateBefore(String appDateBefore) {
		this.appDateBefore = appDateBefore;
	}
	@Transient
	public String getAppDateAfter() {
		return appDateAfter;
	}

	public void setAppDateAfter(String appDateAfter) {
		this.appDateAfter = appDateAfter;
	}
	@Transient
	public WorkFlowTasksModel getTaskModel() {
		return taskModel;
	}

	public void setTaskModel(WorkFlowTasksModel taskModel) {
		this.taskModel = taskModel;
	}
	@Transient
	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}
	@Transient
	public String getTaskID() {
		return taskID;
	}

	public void setTaskID(String taskID) {
		this.taskID = taskID;
	}
	@Transient
	public String getFormKey() {
		return formKey;
	}

	public void setFormKey(String formKey) {
		this.formKey = formKey;
	}
	@Transient
	public String getAssistant() {
		return assistant;
	}

	public void setAssistant(String assistant) {
		this.assistant = assistant;
	}
	@Transient
	public String getIsSuccess() {
		return isSuccess;
	}

	public void setIsSuccess(String isSuccess) {
		this.isSuccess = isSuccess;
	}
	@Transient
	public String getResourcesName() {
		return resourcesName;
	}

	public void setResourcesName(String resourcesName) {
		this.resourcesName = resourcesName;
	}
	@Transient
	public String getDefinitionKey() {
		return definitionKey;
	}

	public void setDefinitionKey(String definitionKey) {
		this.definitionKey = definitionKey;
	}
	@Transient
	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}
	
	
}
