package com.oasys.model;

// Generated 2015-10-27 14:20:59 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.springframework.format.annotation.DateTimeFormat;

import com.oasys.viewModel.WorkFlowTasksModel;

/**
 * TOaPdLeaveApp generated by hbm2java
 */
@Entity
@Table(name = "t_oa_pd_leave_app", catalog = "oasys", uniqueConstraints = @UniqueConstraint(columnNames = "APP_NO"))
public class LeaveApp implements java.io.Serializable {

	private Integer leaId;
	private String appNo;
	private Integer applicantNo;
	private String position;
	private Integer deptNo;
	private Date appDate;
	private String appStatus;
	private String leType;
	private String leTypeOther;
	private Integer agentNo;
	private String leReason;
	private Date planBgDtime;
	private Date planEdDtime;
	private BigDecimal planLeDays;
	private Date realBgDtime;
	private Date realEdDtime;
	private BigDecimal realLeDays;
	private String procStatus;
	private String remark;
	
	/**
	 *申请人姓名 
	 */
	private String applicantName;
	/**
	 * 部门名称
	 */
	private String fullName;
	/**
	 * 代理人姓名
	 */
	private String agentName;
	/**
	 * //开始申请时间
	 */
	private String appDateS;
	/**
	 * //结束时间
	 */
	private String appDateE;
	/**
	 * 申请状态名成
	 */
	private String appStatusName;
	/**
	 * 请假名称
	 */
	private String leName;

	/** WorkFlow propertites */
	private WorkFlowTasksModel taskModel;//task对象
	private String result;//审批通过或驳回标识
	private String taskID;//任务taskID
	private String formKey;//跳转对应的受理页面JSP配置(在流程图的formKey中设置)
	private String assistant;//指定的候选人
	private String isSuccess;//是否通过标识
	private String ideaRemark;//审批意见
	private String definitionKey;//流程表示key

	public LeaveApp() {
	}

	

	public LeaveApp(Integer leaId, String appNo, Integer applicantNo,
			String position, Integer deptNo, Date appDate, String appStatus,
			String leType, String leTypeOther, Integer agentNo,
			String leReason, Date planBgDtime, Date planEdDtime,
			BigDecimal planLeDays, Date realBgDtime, Date realEdDtime,
			BigDecimal realLeDays, String procStatus, String remark,
			String applicantName, String fullName, String agentName,
			String appDateS, String appDateE, String appStatusName,
			String leName, WorkFlowTasksModel taskModel,
			String result, String taskID, String formKey, String assistant,
			String isSuccess, String ideaRemark, String definitionKey) {
		super();
		this.leaId = leaId;
		this.appNo = appNo;
		this.applicantNo = applicantNo;
		this.position = position;
		this.deptNo = deptNo;
		this.appDate = appDate;
		this.appStatus = appStatus;
		this.leType = leType;
		this.leTypeOther = leTypeOther;
		this.agentNo = agentNo;
		this.leReason = leReason;
		this.planBgDtime = planBgDtime;
		this.planEdDtime = planEdDtime;
		this.planLeDays = planLeDays;
		this.realBgDtime = realBgDtime;
		this.realEdDtime = realEdDtime;
		this.realLeDays = realLeDays;
		this.procStatus = procStatus;
		this.remark = remark;
		this.applicantName = applicantName;
		this.fullName = fullName;
		this.agentName = agentName;
		this.appDateS = appDateS;
		this.appDateE = appDateE;
		this.appStatusName = appStatusName;
		this.leName = leName;
		this.taskModel = taskModel;
		this.result = result;
		this.taskID = taskID;
		this.formKey = formKey;
		this.assistant = assistant;
		this.isSuccess = isSuccess;
		this.ideaRemark = ideaRemark;
		this.definitionKey = definitionKey;
	}

	
	@Transient
	public String getApplicantName() {
		return applicantName;
	}


	public void setApplicantName(String applicantName) {
		this.applicantName = applicantName;
	}

	@Transient
	public String getFullName() {
		return fullName;
	}


	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Transient
	public String getAgentName() {
		return agentName;
	}



	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}


	@Transient
	public String getAppDateS() {
		return appDateS;
	}



	public void setAppDateS(String appDateS) {
		this.appDateS = appDateS;
	}


	@Transient
	public String getAppDateE() {
		return appDateE;
	}



	public void setAppDateE(String appDateE) {
		this.appDateE = appDateE;
	}


	@Transient
	public String getAppStatusName() {
		return appStatusName;
	}



	public void setAppStatusName(String appStatusName) {
		this.appStatusName = appStatusName;
	}


	@Transient
	public String getLeName() {
		return leName;
	}



	public void setLeName(String leName) {
		this.leName = leName;
	}


	@Transient
	public WorkFlowTasksModel getTaskModel() {
		return taskModel;
	}



	public void setTaskModel(WorkFlowTasksModel taskModel) {
		this.taskModel = taskModel;
	}


	@Transient
	public String getResult() {
		return result;
	}



	public void setResult(String result) {
		this.result = result;
	}


	@Transient
	public String getTaskID() {
		return taskID;
	}



	public void setTaskID(String taskID) {
		this.taskID = taskID;
	}


	@Transient
	public String getFormKey() {
		return formKey;
	}



	public void setFormKey(String formKey) {
		this.formKey = formKey;
	}


	@Transient
	public String getAssistant() {
		return assistant;
	}



	public void setAssistant(String assistant) {
		this.assistant = assistant;
	}


	@Transient
	public String getIsSuccess() {
		return isSuccess;
	}



	public void setIsSuccess(String isSuccess) {
		this.isSuccess = isSuccess;
	}


	@Transient
	public String getIdeaRemark() {
		return ideaRemark;
	}



	public void setIdeaRemark(String ideaRemark) {
		this.ideaRemark = ideaRemark;
	}


	@Transient
	public String getDefinitionKey() {
		return definitionKey;
	}



	public void setDefinitionKey(String definitionKey) {
		this.definitionKey = definitionKey;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LEA_ID", unique = true, nullable = false)
	public Integer getLeaId() {
		return this.leaId;
	}

	public void setLeaId(Integer leaId) {
		this.leaId = leaId;
	}

	@Column(name = "APP_NO", unique = true, length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "APPLICANT_NO")
	public Integer getApplicantNo() {
		return this.applicantNo;
	}

	public void setApplicantNo(Integer applicantNo) {
		this.applicantNo = applicantNo;
	}

	@Column(name = "POSITION", length = 50)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "DEPT_NO")
	public Integer getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(Integer deptNo) {
		this.deptNo = deptNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APP_DATE", length = 10)
	@DateTimeFormat(pattern="yyyy-MM-dd")
	public Date getAppDate() {
		return this.appDate;
	}

	public void setAppDate(Date appDate) {
		this.appDate = appDate;
	}

	@Column(name = "APP_STATUS", length = 100)
	public String getAppStatus() {
		return this.appStatus;
	}

	public void setAppStatus(String appStatus) {
		this.appStatus = appStatus;
	}

	@Column(name = "LE_TYPE", length = 1)
	public String getLeType() {
		return this.leType;
	}

	public void setLeType(String leType) {
		this.leType = leType;
	}

	@Column(name = "LE_TYPE_OTHER", length = 20)
	public String getLeTypeOther() {
		return this.leTypeOther;
	}

	public void setLeTypeOther(String leTypeOther) {
		this.leTypeOther = leTypeOther;
	}

	@Column(name = "AGENT_NO")
	public Integer getAgentNo() {
		return this.agentNo;
	}

	public void setAgentNo(Integer agentNo) {
		this.agentNo = agentNo;
	}

	@Column(name = "LE_REASON", length = 200)
	public String getLeReason() {
		return this.leReason;
	}

	public void setLeReason(String leReason) {
		this.leReason = leReason;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PLAN_BG_DTIME", length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getPlanBgDtime() {
		return this.planBgDtime;
	}

	public void setPlanBgDtime(Date planBgDtime) {
		this.planBgDtime = planBgDtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PLAN_ED_DTIME", length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getPlanEdDtime() {
		return this.planEdDtime;
	}

	public void setPlanEdDtime(Date planEdDtime) {
		this.planEdDtime = planEdDtime;
	}

	@Column(name = "PLAN_LE_DAYS", precision = 4, scale = 1)
	public BigDecimal getPlanLeDays() {
		return this.planLeDays;
	}

	public void setPlanLeDays(BigDecimal planLeDays) {
		this.planLeDays = planLeDays;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REAL_BG_DTIME", length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getRealBgDtime() {
		return this.realBgDtime;
	}

	public void setRealBgDtime(Date realBgDtime) {
		this.realBgDtime = realBgDtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REAL_ED_DTIME", length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getRealEdDtime() {
		return this.realEdDtime;
	}

	public void setRealEdDtime(Date realEdDtime) {
		this.realEdDtime = realEdDtime;
	}

	@Column(name = "REAL_LE_DAYS", precision = 4, scale = 1)
	public BigDecimal getRealLeDays() {
		return this.realLeDays;
	}

	public void setRealLeDays(BigDecimal realLeDays) {
		this.realLeDays = realLeDays;
	}

	@Column(name = "PROC_STATUS", length = 1)
	public String getProcStatus() {
		return this.procStatus;
	}

	public void setProcStatus(String procStatus) {
		this.procStatus = procStatus;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
