/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-12-31 08:10:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.investproducts;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class addOrUpdateInvestProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\t\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t//加载页面时，初始化还款方式下拉列表\r\n");
      out.write("\t\t$('#repaymentMode').combobox({    \t\t\t    \r\n");
      out.write("\t\t\turl:\"common/commonAction!findTextArr.action?codeMyid=repayment_mode\",\r\n");
      out.write("\t\t\tvalueField: 'code',\r\n");
      out.write("\t\t\ttextField: 'text'\t\t\t    \t\t\t    \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//加载页面时，初始化还产品状态列表\r\n");
      out.write("\t\t$('#prodStatus').combobox({    \t\t\t    \r\n");
      out.write("\t\t\turl:\"common/commonAction!findTextArr.action?codeMyid=prod_status\",\r\n");
      out.write("\t\t\tvalueField: 'code',\r\n");
      out.write("\t\t\ttextField: 'text'\t\t\t    \t\t\t    \r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t});\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 清空新添加的理财产品的的数据**/\r\n");
      out.write("\tfunction clearForm(){\t\r\n");
      out.write("\t\t$.messager.confirm('警告', '是否确定重置此款理财产品的信息？</br>这会将本款理财产品的信息清空!!!', function(flag) {\r\n");
      out.write("\t\t\tif(flag){\r\n");
      out.write("\t\t\t\t$(\"#investProductInputOrSaveForm\").form(\"clear\");\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 增加或者修改理财产品的数据**/\r\n");
      out.write("\tfunction saveInvestProductInfo(){\r\n");
      out.write("\t\t//校验理财产品输入的信息\r\n");
      out.write("   \t\tvar isValid = $(\"#investProductInputOrSaveForm\").form('validate');\r\n");
      out.write("    \tif(!isValid){\r\n");
      out.write("    \t\treturn false;\r\n");
      out.write("    \t} \r\n");
      out.write("    \t     \t    \t\r\n");
      out.write("    \tvar lowLendEdu = $(\"#lowLendEdu\").val();\r\n");
      out.write("    \tif(lowLendEdu == \"\" ){\r\n");
      out.write("    \t\t$(\"#lowLendEdu\").val(null);\r\n");
      out.write("    \t}\r\n");
      out.write("\r\n");
      out.write("    \tvar higLendEdu = $(\"#higLendEdu\").val();\r\n");
      out.write("    \tif(higLendEdu == \"\" ){\r\n");
      out.write("    \t\t$(\"#higLendEdu\").val(null);\r\n");
      out.write("    \t}    \t\r\n");
      out.write("    \t    \r\n");
      out.write("    \t$.ajax({\r\n");
      out.write("    \t\ttype: \"POST\",\r\n");
      out.write("    \t\turl:\"investProduct/investProductAction!persistenceInvestProduct.action\",\r\n");
      out.write("    \t\tdata:$('#investProductInputOrSaveForm').serialize(),\r\n");
      out.write("    \t\tasync: false,//默认true设置下，所有请求均为异步请求\r\n");
      out.write("    \t\tcache: true,\r\n");
      out.write("    \t    success: function(iJson) {    \t    \t\r\n");
      out.write("     \t    \tif(iJson.status){\r\n");
      out.write("    \t    \t\t$(\"#prodId\").val(iJson.data);//成功保存理财产品ID    \t    \t\t\r\n");
      out.write("    \t    \t\t$(\"#saveOrUpdateInvestProductDialog\").dialog(\"close\");//关闭弹窗\r\n");
      out.write("    \t    \t\t$(\"#dg\").datagrid(\"reload\");//刷新表格    \t    \t\t\r\n");
      out.write("    \t    \t\t/* disableForm();//禁用form */\r\n");
      out.write("    \t    \t}\r\n");
      out.write("    \t    \tparent.$.messager.show({\r\n");
      out.write("    \t\t\t\ttitle : '提示',\r\n");
      out.write("    \t\t\t\tmsg : iJson.message,\r\n");
      out.write("    \t\t\t\ttimeout : 4000 * 2\r\n");
      out.write("    \t\t\t}); \r\n");
      out.write("    \t    }\r\n");
      out.write("    \t});\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/**根据用户填入的理财产品周期，动态的设置本页面中的年化折标系数\r\n");
      out.write("\t\t年化折标系数：\r\n");
      out.write("\t\t\t45T->0.2\r\n");
      out.write("\t\t\t90T->0.25 1/(360/90)\r\n");
      out.write("\t\t\t180T->0.5 1/(360/180)\r\n");
      out.write("\t\t\t365T->1 1(/360/360)\r\n");
      out.write("\t**/\r\n");
      out.write("\tfunction decideMsfByLendingCycle(){\r\n");
      out.write("\t\tvar lendingCyle = $(\"#lendingCycle\").val();\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//判断用户输入是否为NULL或者空字符\r\n");
      out.write("\t\tif(lendingCyle ==\"\" || lendingCyle == null){\r\n");
      out.write("\t\t\t$.messager.alert(\"提示\", \"请输入出借天数\",\"warning\");\r\n");
      out.write("\t\t\t$(\"#lendingCycle\").focus();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(lendingCyle == '45'){\r\n");
      out.write("\t\t\t\t$(\"#msf\").val(\"0.2\");    \r\n");
      out.write("\t\t\t}else if(lendingCyle == '90'){\r\n");
      out.write("\t\t\t\t$(\"#msf\").val(\"0.25\");   \r\n");
      out.write("\t\t\t}else if(lendingCyle == '180'){\r\n");
      out.write("\t\t\t\t$(\"#msf\").val(\"0.5\");   \r\n");
      out.write("\t\t\t}else if(lendingCyle == '365'){\r\n");
      out.write("\t\t\t\t$(\"#msf\").val(\"1\");   \r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#msf\").val(\"\");\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"margin-left: 5px;margin-top: 5px;\">\r\n");
      out.write("\t   <form id=\"investProductInputOrSaveForm\" method=\"post\">\r\n");
      out.write("\t   \t\t<input id=\"prodId\" name=\"prodId\" type=\"hidden\"/><!--理财产品的ID -->\r\n");
      out.write("\t\t\t<table class=\"table\" width=\"80%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>产品名称:</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"prodName\" name=\"prodName\" class=\"easyui-textbox easyui-validatebox\" data-options=\"validType:'length[0,100]', required:true\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t    <th>出借周期(天):</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"lendingCycle\" name=\"lendingCycle\" type=\"text\" class=\"easyui-textbox easyui-validatebox\" data-options=\"validType:'integer',required:true\" onblur=\"decideMsfByLendingCycle()\" onchange=\"decideMsfByLendingCycle()\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>年化收益率:</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"ars\" name=\"ars\" type=\"text\" class=\"easyui-textbox easyui-validatebox\" data-options=\"validType:'intOrFloat',required:true\"/>%\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th>到期收益率:</th>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"ytm\" name=\"ytm\" type=\"text\" class=\"easyui-textbox easyui-validatebox\" data-options=\"validType:'intOrFloat',required:true\"/>%\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>最低出借金额(元):</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"lowLendEdu\" name=\"lowLendEdu\" type=\"text\" class=\"easyui-textbox easyui-validatebox\" data-options=\"validType:'intOrFloat',required:true\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>最高出借金额(元):</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"higLendEdu\" name=\"higLendEdu\" type=\"text\" class=\"easyui-textbox easyui-validatebox\" data-options=\"validType:'intOrFloat'\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>还款方式:</th>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"repaymentMode\" name=\"repaymentMode\" class=\"easyui-combobox easyui-validatebox\" data-options=\"panelHeight:50\"/></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th>产品状态:</th>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"prodStatus\" name=\"prodStatus\" class=\"easyui-combobox easyui-validatebox\" data-options=\"panelHeight:50\"/></td>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t    <th>产品描述:</th>\r\n");
      out.write("\t\t\t\t    <td><input name=\"prodDesc\" class=\"easyui-textbox\" data-options=\"validType:'length[0,100]'\"/></td>\t\t\t\t    \r\n");
      out.write("\t\t\t\t    <th>年化折标系数：</th>\r\n");
      out.write("\t\t\t\t    <td>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"msf\" name=\"msf\" class=\"easyui-textbox\" style=\"width:150px;\" readonly=\"readonly\"/>   \r\n");
      out.write("\t\t\t\t    </td>\t\t\t    \r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t   <td colspan=\"4\" align=\"right\">\r\n");
      out.write("\t\t\t\t      <a href=\"javascript:void(0)\" id=\"rset\" class=\"easyui-linkbutton\" iconCls=\"icon-reload\" onclick=\"clearForm();\">重置</a>\r\n");
      out.write("\t\t\t\t      <a href=\"javascript:void(0)\" id=\"save\" class=\"easyui-linkbutton\" iconCls=\"icon-save\" onclick=\"saveInvestProductInfo();\">保存</a>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\t\t\t\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
