package com.oasys.model;

// Generated 2015-11-10 20:50:13 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.springframework.format.annotation.DateTimeFormat;

import com.oasys.viewModel.WorkFlowTasksModel;

/**
 * TOaPdBusinessTripApp generated by hbm2java
 */
@Entity
@Table(name = "t_oa_pd_business_trip_app", uniqueConstraints = @UniqueConstraint(columnNames = "APP_NO"))
public class BusinessTripApp implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer btaId;
	private String appNo;
	private Integer applicantNo;
	private String userName;
	private String position;
	private Integer deptNo;
	private String deptName;
	private Date appDate;
	private String appStatus;
	private String btReason;
	private Integer agentNo;
	private String agentName;
	private String procStatus;
	private String remark;
	private BusinessTripAttach businessTripAttach;
	private String appDateBefore;//查询申请时间开始绑定字段
	private String appDateAfter;//查询申请时间结束绑定字段
	private WorkFlowTasksModel taskModel;//task对象
	private String result;//审批通过或驳回标识
	private String taskID;//任务taskID
	private String formKey;//跳转对应的受理页面JSP配置(在流程图的formKey中设置)
	private String assistant;//指定的候选人
	private String isSuccess;//是否通过标识
	private String resourcesName;//资源文件名称
	private String definitionKey;//流程标识Key
	private String formKeyJson;
	public BusinessTripApp() {
	}

	public BusinessTripApp(String appNo, Integer applicantNo,
			String position, Integer deptNo, Date appDate, String appStatus,
			String btReason, Integer agentNo, String procStatus,
			String remark,BusinessTripAttach businessTripAttach) {
		this.appNo = appNo;
		this.applicantNo = applicantNo;
		this.position = position;
		this.deptNo = deptNo;
		this.appDate = appDate;
		this.appStatus = appStatus;
		this.btReason = btReason;
		this.agentNo = agentNo;
		this.procStatus = procStatus;
		this.remark = remark;
		this.businessTripAttach=businessTripAttach;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BTA_ID", unique = true, nullable = false)
	public Integer getBtaId() {
		return this.btaId;
	}

	public void setBtaId(Integer btaId) {
		this.btaId = btaId;
	}

	@Column(name = "APP_NO", unique = true, length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "APPLICANT_NO")
	public Integer getApplicantNo() {
		return this.applicantNo;
	}

	public void setApplicantNo(Integer applicantNo) {
		this.applicantNo = applicantNo;
	}

	@Column(name = "POSITION", length = 50)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "DEPT_NO")
	public Integer getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(Integer deptNo) {
		this.deptNo = deptNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APP_DATE", length = 10)
	@DateTimeFormat(pattern="yyyy-MM-dd")
	public Date getAppDate() {
		return this.appDate;
	}

	public void setAppDate(Date appDate) {
		this.appDate = appDate;
	}

	@Column(name = "APP_STATUS", length = 100)
	public String getAppStatus() {
		return this.appStatus;
	}

	public void setAppStatus(String appStatus) {
		this.appStatus = appStatus;
	}

	@Column(name = "BT_REASON", length = 200)
	public String getBtReason() {
		return this.btReason;
	}

	public void setBtReason(String btReason) {
		this.btReason = btReason;
	}

	@Column(name = "AGENT_NO")
	public Integer getAgentNo() {
		return this.agentNo;
	}

	public void setAgentNo(Integer agentNo) {
		this.agentNo = agentNo;
	}

	@Column(name = "PROC_STATUS", length = 1)
	public String getProcStatus() {
		return this.procStatus;
	}

	public void setProcStatus(String procStatus) {
		this.procStatus = procStatus;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	/*@OneToOne(cascade=CascadeType.ALL)
	@PrimaryKeyJoinColumn*/
	@Transient
	public BusinessTripAttach getBusinessTripAttach() {
		return businessTripAttach;
	}

	public void setBusinessTripAttach(BusinessTripAttach businessTripAttach) {
		this.businessTripAttach = businessTripAttach;
	}
	@Transient
	public String getAppDateBefore() {
		return appDateBefore;
	}

	public void setAppDateBefore(String appDateBefore) {
		this.appDateBefore = appDateBefore;
	}
	@Transient
	public String getAppDateAfter() {
		return appDateAfter;
	}

	public void setAppDateAfter(String appDateAfter) {
		this.appDateAfter = appDateAfter;
	}
	@Transient
	public WorkFlowTasksModel getTaskModel() {
		return taskModel;
	}

	public void setTaskModel(WorkFlowTasksModel taskModel) {
		this.taskModel = taskModel;
	}
	@Transient
	public String getResult() {
		return result;
	}
	
	public void setResult(String result) {
		this.result = result;
	}
	@Transient
	public String getTaskID() {
		return taskID;
	}

	public void setTaskID(String taskID) {
		this.taskID = taskID;
	}
	@Transient
	public String getFormKey() {
		return formKey;
	}

	public void setFormKey(String formKey) {
		this.formKey = formKey;
	}
	@Transient
	public String getAssistant() {
		return assistant;
	}

	public void setAssistant(String assistant) {
		this.assistant = assistant;
	}
	@Transient
	public String getIsSuccess() {
		return isSuccess;
	}

	public void setIsSuccess(String isSuccess) {
		this.isSuccess = isSuccess;
	}
	@Transient
	public String getResourcesName() {
		return resourcesName;
	}

	public void setResourcesName(String resourcesName) {
		this.resourcesName = resourcesName;
	}
	@Transient
	public String getDefinitionKey() {
		return definitionKey;
	}

	public void setDefinitionKey(String definitionKey) {
		this.definitionKey = definitionKey;
	}
	@Transient
	public String getFormKeyJson() {
		return formKeyJson;
	}

	public void setFormKeyJson(String formKeyJson) {
		this.formKeyJson = formKeyJson;
	}
	@Transient
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	@Transient
	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}
	@Transient
	public String getAgentName() {
		return agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}
	
	
}
