package com.oasys.model;

// Generated 2015-10-26 10:41:42 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.oasys.viewModel.WorkFlowTasksModel;

/**
 * TOaHrEmpSalPositionChgApp generated by hbm2java
 */
@Entity
@Table(name = "t_oa_hr_emp_sal_position_chg_app", uniqueConstraints = @UniqueConstraint(columnNames = "APP_NO"))
public class EmpSalPositionChgApp implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 1L;

	private Integer efaId;//主键ID
	private String appNo;//申请编号
	private String appDate;//申请日期
	private Integer applicantNo;//申请人
	private Integer curDeptNo;//目前部门ID
	private String curDeptName;//目前部门名称
	private String curPosition;//目前所在职位 职位ID(roleID)
	private String curPositionStr;//目前所在职位 职位显示名称(roleName)
	private BigDecimal curSal;//目前薪资
	private String curWorking;//目前工作内容
	private String entryDate;//如之日起
	private String chgType;//异动事由
	private Integer aftDeptNo;//调整后部门ID
	private String aftDeptName;//调整后部门名称
	private String aftPosition;//调整后职位 职位ID(roleID)
	private String aftPositionStr;//调整后职位 职位显示名称(roleName)
	private BigDecimal aftSal;//调整后薪资
	private String aftWorking;//调整后工作内容
	private String salChgMode;//薪资调整形式
	private String chgReson;//变动理由
	private String chgResonOther;//其他变动理由
	private String effectiveDate;//申请生效日期
	private Integer trialPeriods;//试岗期限
	private BigDecimal trialSal;//试岗月薪
	private String remark;//备注
	private String procStatus;//流程状态
	private String appStatus;//申请状态

	private String userName;// 用户名称
	private String chgTypeName;//异动事由名称
	private String salChgTypeName;//薪资调整形式名称
	private String chgResonName;//变动理由名称
	private String appDateBefore;//查询申请时间开始绑定字段
	private String appDateAfter;//查询申请时间结束绑定字段
	/** WorkFlow propertites */
	private WorkFlowTasksModel taskModel;// task对象
	private String result;// 审批通过或驳回标识
	private String taskID;// 任务taskID
	private String formKey;// 跳转对应的受理页面JSP配置(在流程图的formKey中设置)
	/** 各个节点配置的判断与跳转控制json 
	 *   如果formKey中不设置Json跳转控制 那么默认有 通过 拒绝 驳回操作 并且 通过操作会默认传递 "1" 来进行跳转下一流程
	 *   格式为：formKey?{"type":0,"JK":"ChengShiJingLi","CF":"YingYeBuJingLi"} -----该格式跳转借款端或财富端格式
	 *   			  formKey?{"type":1,"result1":"YX1","result2":"YS1","result3":"TuanDuiJingLi"} -----该格式为判断团队经理以上或团队经理以下格式
	 *   			  formKey?{"type":2} ----该格式为只有通过和驳回操作
	 *   			  formKey?{"type":3} ----该格式为只有通过操作*/ 
	private String formKeyJson;
	
	private String assistant;// 指定的候选人
	private String isSuccess;// 是否通过标识
	private String resourcesName;// 资源文件名称
	private String definitionKey;// 流程标识Key

	
	public EmpSalPositionChgApp() {
		super();
		// TODO Auto-generated constructor stub
	}

	public EmpSalPositionChgApp(Integer efaId, String appNo, String appDate,
			Integer applicantNo, Integer curDeptNo, String curDeptName,
			String curPosition, BigDecimal curSal, String curWorking,
			String entryDate, String chgType, Integer aftDeptNo,
			String aftDeptName, String aftPosition, BigDecimal aftSal,
			String aftWorking, String salChgMode, String chgReson,
			String chgResonOther, String effectiveDate, Integer trialPeriods,
			BigDecimal trialSal, String remark, String procStatus,
			String appStatus, String userName, String chgTypeName,
			String salChgTypeName, String chgResonName, String appDateBefore,
			String appDateAfter, WorkFlowTasksModel taskModel, String result,
			String taskID, String formKey, String formKeyJson,
			String assistant, String isSuccess, String resourcesName,
			String definitionKey) {
		super();
		this.efaId = efaId;
		this.appNo = appNo;
		this.appDate = appDate;
		this.applicantNo = applicantNo;
		this.curDeptNo = curDeptNo;
		this.curDeptName = curDeptName;
		this.curPosition = curPosition;
		this.curSal = curSal;
		this.curWorking = curWorking;
		this.entryDate = entryDate;
		this.chgType = chgType;
		this.aftDeptNo = aftDeptNo;
		this.aftDeptName = aftDeptName;
		this.aftPosition = aftPosition;
		this.aftSal = aftSal;
		this.aftWorking = aftWorking;
		this.salChgMode = salChgMode;
		this.chgReson = chgReson;
		this.chgResonOther = chgResonOther;
		this.effectiveDate = effectiveDate;
		this.trialPeriods = trialPeriods;
		this.trialSal = trialSal;
		this.remark = remark;
		this.procStatus = procStatus;
		this.appStatus = appStatus;
		this.userName = userName;
		this.chgTypeName = chgTypeName;
		this.salChgTypeName = salChgTypeName;
		this.chgResonName = chgResonName;
		this.appDateBefore = appDateBefore;
		this.appDateAfter = appDateAfter;
		this.taskModel = taskModel;
		this.result = result;
		this.taskID = taskID;
		this.formKey = formKey;
		this.formKeyJson = formKeyJson;
		this.assistant = assistant;
		this.isSuccess = isSuccess;
		this.resourcesName = resourcesName;
		this.definitionKey = definitionKey;
	}

	

	@Transient
	public String getCurPositionStr() {
		return curPositionStr;
	}

	public void setCurPositionStr(String curPositionStr) {
		this.curPositionStr = curPositionStr;
	}
	@Transient
	public String getAftPositionStr() {
		return aftPositionStr;
	}

	public void setAftPositionStr(String aftPositionStr) {
		this.aftPositionStr = aftPositionStr;
	}
	
	@Transient
	public String getFormKeyJson() {
		return formKeyJson;
	}

	public void setFormKeyJson(String formKeyJson) {
		this.formKeyJson = formKeyJson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EFA_ID", unique = true, nullable = false)
	public Integer getEfaId() {
		return this.efaId;
	}

	public void setEfaId(Integer efaId) {
		this.efaId = efaId;
	}

	@Column(name = "APP_NO", unique = true, length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "PROC_STATUS")
	public String getProcStatus() {
		return procStatus;
	}

	public void setProcStatus(String procStatus) {
		this.procStatus = procStatus;
	}
	
	
	@Column(name = "APP_DATE", length = 10)
	public String getAppDate() {
		return this.appDate;
	}

	public void setAppDate(String appDate) {
		this.appDate = appDate;
	}

	@Column(name = "APPLICANT_NO")
	public Integer getApplicantNo() {
		return this.applicantNo;
	}

	public void setApplicantNo(Integer applicantNo) {
		this.applicantNo = applicantNo;
	}

	@Column(name = "CUR_DEPT_NO")
	public Integer getCurDeptNo() {
		return this.curDeptNo;
	}

	public void setCurDeptNo(Integer curDeptNo) {
		this.curDeptNo = curDeptNo;
	}

	@Column(name = "CUR_DEPT_NAME", length = 50)
	public String getCurDeptName() {
		return this.curDeptName;
	}

	public void setCurDeptName(String curDeptName) {
		this.curDeptName = curDeptName;
	}

	@Column(name = "CUR_POSITION", length = 50)
	public String getCurPosition() {
		return this.curPosition;
	}

	public void setCurPosition(String curPosition) {
		this.curPosition = curPosition;
	}

	@Column(name = "CUR_SAL", precision = 10)
	public BigDecimal getCurSal() {
		return this.curSal;
	}

	public void setCurSal(BigDecimal curSal) {
		this.curSal = curSal;
	}

	@Column(name = "CUR_WORKING", length = 250)
	public String getCurWorking() {
		return this.curWorking;
	}

	public void setCurWorking(String curWorking) {
		this.curWorking = curWorking;
	}

	@Column(name = "ENTRY_DATE", length = 10)
	public String getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(String entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "CHG_TYPE")
	public String getChgType() {
		return this.chgType;
	}

	public void setChgType(String chgType) {
		this.chgType = chgType;
	}

	@Column(name = "AFT_DEPT_NO")
	public Integer getAftDeptNo() {
		return this.aftDeptNo;
	}

	public void setAftDeptNo(Integer aftDeptNo) {
		this.aftDeptNo = aftDeptNo;
	}

	@Column(name = "AFT_DEPT_NAME", length = 50)
	public String getAftDeptName() {
		return this.aftDeptName;
	}

	public void setAftDeptName(String aftDeptName) {
		this.aftDeptName = aftDeptName;
	}

	@Column(name = "AFT_POSITION", length = 50)
	public String getAftPosition() {
		return this.aftPosition;
	}

	public void setAftPosition(String aftPosition) {
		this.aftPosition = aftPosition;
	}

	@Column(name = "AFT_SAL", precision = 10)
	public BigDecimal getAftSal() {
		return this.aftSal;
	}

	public void setAftSal(BigDecimal aftSal) {
		this.aftSal = aftSal;
	}

	@Column(name = "AFT_WORKING", length = 250)
	public String getAftWorking() {
		return this.aftWorking;
	}

	public void setAftWorking(String aftWorking) {
		this.aftWorking = aftWorking;
	}

	@Column(name = "SAL_CHG_MODE")
	public String getSalChgMode() {
		return this.salChgMode;
	}

	public void setSalChgMode(String salChgMode) {
		this.salChgMode = salChgMode;
	}

	@Column(name = "CHG_RESON")
	public String getChgReson() {
		return this.chgReson;
	}

	public void setChgReson(String chgReson) {
		this.chgReson = chgReson;
	}

	@Column(name = "CHG_RESON_OTHER", length = 100)
	public String getChgResonOther() {
		return this.chgResonOther;
	}

	public void setChgResonOther(String chgResonOther) {
		this.chgResonOther = chgResonOther;
	}

	@Column(name = "EFFECTIVE_DATE", length = 10)
	public String getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(String effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Column(name = "TRIAL_PERIODS")
	public Integer getTrialPeriods() {
		return this.trialPeriods;
	}

	public void setTrialPeriods(Integer trialPeriods) {
		this.trialPeriods = trialPeriods;
	}

	@Column(name = "TRIAL_SAL", precision = 10)
	public BigDecimal getTrialSal() {
		return this.trialSal;
	}

	public void setTrialSal(BigDecimal trialSal) {
		this.trialSal = trialSal;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}
	
	@Column(name = "APP_STATUS")
	public String getAppStatus() {
		return appStatus;
	}

	public void setAppStatus(String appStatus) {
		this.appStatus = appStatus;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Transient
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	
	@Transient
	public String getChgTypeName() {
		return chgTypeName;
	}

	public void setChgTypeName(String chgTypeName) {
		this.chgTypeName = chgTypeName;
	}
	
	@Transient
	public String getSalChgTypeName() {
		return salChgTypeName;
	}

	public void setSalChgTypeName(String salChgTypeName) {
		this.salChgTypeName = salChgTypeName;
	}

	@Transient
	public String getChgResonName() {
		return chgResonName;
	}

	public void setChgResonName(String chgResonName) {
		this.chgResonName = chgResonName;
	}

	@Transient
	public WorkFlowTasksModel getTaskModel() {
		return taskModel;
	}

	public void setTaskModel(WorkFlowTasksModel taskModel) {
		this.taskModel = taskModel;
	}

	@Transient
	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Transient
	public String getTaskID() {
		return taskID;
	}

	public void setTaskID(String taskID) {
		this.taskID = taskID;
	}

	@Transient
	public String getFormKey() {
		return formKey;
	}

	public void setFormKey(String formKey) {
		this.formKey = formKey;
	}

	@Transient
	public String getAssistant() {
		return assistant;
	}

	public void setAssistant(String assistant) {
		this.assistant = assistant;
	}

	@Transient
	public String getIsSuccess() {
		return isSuccess;
	}

	public void setIsSuccess(String isSuccess) {
		this.isSuccess = isSuccess;
	}

	@Transient
	public String getResourcesName() {
		return resourcesName;
	}

	public void setResourcesName(String resourcesName) {
		this.resourcesName = resourcesName;
	}

	@Transient
	public String getDefinitionKey() {
		return definitionKey;
	}

	public void setDefinitionKey(String definitionKey) {
		this.definitionKey = definitionKey;
	}

	@Transient
	public String getAppDateBefore() {
		return appDateBefore;
	}

	public void setAppDateBefore(String appDateBefore) {
		this.appDateBefore = appDateBefore;
	}
	@Transient
	public String getAppDateAfter() {
		return appDateAfter;
	}

	public void setAppDateAfter(String appDateAfter) {
		this.appDateAfter = appDateAfter;
	}

	
	
}
