package com.oasys.model;

// Generated 2015-12-9 20:15:16 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOaPdNoticeInfo generated by hbm2java
 */
@Entity
@Table(name = "t_oa_pd_notice_info")
public class NoticeInfo implements java.io.Serializable {

	private Integer noiId;
	private String noticeNo;
	private Integer sender;
	private Date sendDtime;
	private String topic;
	private String noticeGrade;
	private String noticeContent;
	private String sentStatus;
	private String isNeedReceipt;
	private String isAllReceipted;
	private String isHaveAtt;
	private String remark;

	public NoticeInfo() {
	}

	public NoticeInfo(String noticeNo, Integer sender, Date sendDtime,
			String topic, String noticeGrade, String noticeContent,
			String sentStatus, String isNeedReceipt,
			String isAllReceipted, String isHaveAtt, String remark) {
		this.noticeNo = noticeNo;
		this.sender = sender;
		this.sendDtime = sendDtime;
		this.topic = topic;
		this.noticeGrade = noticeGrade;
		this.noticeContent = noticeContent;
		this.sentStatus = sentStatus;
		this.isNeedReceipt = isNeedReceipt;
		this.isAllReceipted = isAllReceipted;
		this.isHaveAtt = isHaveAtt;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NOI_ID", unique = true, nullable = false)
	public Integer getNoiId() {
		return this.noiId;
	}

	public void setNoiId(Integer noiId) {
		this.noiId = noiId;
	}

	@Column(name = "NOTICE_NO", length = 25)
	public String getNoticeNo() {
		return this.noticeNo;
	}

	public void setNoticeNo(String noticeNo) {
		this.noticeNo = noticeNo;
	}

	@Column(name = "SENDER")
	public Integer getSender() {
		return this.sender;
	}

	public void setSender(Integer sender) {
		this.sender = sender;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SEND_DTIME", length = 19)
	public Date getSendDtime() {
		return this.sendDtime;
	}

	public void setSendDtime(Date sendDtime) {
		this.sendDtime = sendDtime;
	}

	@Column(name = "TOPIC", length = 128)
	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	@Column(name = "NOTICE_GRADE", length = 1)
	public String getNoticeGrade() {
		return this.noticeGrade;
	}

	public void setNoticeGrade(String noticeGrade) {
		this.noticeGrade = noticeGrade;
	}

	@Column(name = "NOTICE_CONTENT", length = 5120)
	public String getNoticeContent() {
		return this.noticeContent;
	}

	public void setNoticeContent(String noticeContent) {
		this.noticeContent = noticeContent;
	}

	@Column(name = "SENT_STATUS", length = 1)
	public String getSentStatus() {
		return this.sentStatus;
	}

	public void setSentStatus(String sentStatus) {
		this.sentStatus = sentStatus;
	}

	@Column(name = "IS_NEED_RECEIPT", length = 1)
	public String getIsNeedReceipt() {
		return this.isNeedReceipt;
	}

	public void setIsNeedReceipt(String isNeedReceipt) {
		this.isNeedReceipt = isNeedReceipt;
	}

	@Column(name = "IS_ALL_RECEIPTED", length = 1)
	public String getIsAllReceipted() {
		return this.isAllReceipted;
	}

	public void setIsAllReceipted(String isAllReceipted) {
		this.isAllReceipted = isAllReceipted;
	}

	@Column(name = "IS_HAVE_ATT", length = 1)
	public String getIsHaveAtt() {
		return this.isHaveAtt;
	}

	public void setIsHaveAtt(String isHaveAtt) {
		this.isHaveAtt = isHaveAtt;
	}

	@Column(name = "REMARK", length = 256)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
