package com.oasys.model;

// Generated 2015-12-10 13:43:04 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOaAdParkingFeeInfo generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_parking_fee_info")
public class ParkingFeeInfo implements java.io.Serializable {

	private Integer pfiId;
	private BigDecimal appAmt;
	private Date parkingDtime;
	private String parkingPlace;
	private String remark;

	public ParkingFeeInfo() {
	}

	public ParkingFeeInfo(BigDecimal appAmt, Date parkingDtime,
			String parkingPlace, String remark) {
		this.appAmt = appAmt;
		this.parkingDtime = parkingDtime;
		this.parkingPlace = parkingPlace;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PFI_ID", unique = true, nullable = false)
	public Integer getPfiId() {
		return this.pfiId;
	}

	public void setPfiId(Integer pfiId) {
		this.pfiId = pfiId;
	}

	@Column(name = "APP_AMT", precision = 10)
	public BigDecimal getAppAmt() {
		return this.appAmt;
	}

	public void setAppAmt(BigDecimal appAmt) {
		this.appAmt = appAmt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PARKING_DTIME", length = 10)
	public Date getParkingDtime() {
		return this.parkingDtime;
	}

	public void setParkingDtime(Date parkingDtime) {
		this.parkingDtime = parkingDtime;
	}

	@Column(name = "PARKING_PLACE", length = 256)
	public String getParkingPlace() {
		return this.parkingPlace;
	}

	public void setParkingPlace(String parkingPlace) {
		this.parkingPlace = parkingPlace;
	}

	@Column(name = "REMARK", length = 256)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
