package com.oasys.model;

// Generated 2015-12-4 9:32:01 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * TOaAdPpeUsedConfirmAppAttach generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_ppe_used_confirm_app_attach", catalog = "oasys")
public class PpeUsedConfirmAppAttach implements java.io.Serializable {

	private Integer psaId;
	private String appNo;
	/**固定资产编号*/
	private String ppeNo;
	/**固定资产名称*/
	private String ppeName;
	private Date appDate;
	/**使用用途*/
	private String usedReson;
	/**归还人id*/
	private Integer reverter;
	/**归还日期*/
	private Date givebackDate;
	private String remark;
	/**归还人名字*/
	private String reverterName;
	/**使用性质*/
	private String useNature;
	

	public PpeUsedConfirmAppAttach() {
	}

	public PpeUsedConfirmAppAttach(String appNo, String ppeNo,
			String ppeName, Date appDate, String usedReson, Integer reverter,
			Date givebackDate, String remark,String reverterName,String useNature) {
		this.appNo = appNo;
		this.ppeNo = ppeNo;
		this.ppeName = ppeName;
		this.appDate = appDate;
		this.usedReson = usedReson;
		this.reverter = reverter;
		this.givebackDate = givebackDate;
		this.remark = remark;
		this.reverterName=reverterName;
		this.useNature=useNature;
	}

	@Transient
	public String getUseNature() {
		return useNature;
	}

	public void setUseNature(String useNature) {
		this.useNature = useNature;
	}

	@Transient
	public String getReverterName() {
		return reverterName;
	}

	public void setReverterName(String reverterName) {
		this.reverterName = reverterName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PSA_ID", unique = true, nullable = false)
	public Integer getPsaId() {
		return this.psaId;
	}

	public void setPsaId(Integer psaId) {
		this.psaId = psaId;
	}

	@Column(name = "APP_NO", length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "PPE_NO", length = 27)
	public String getPpeNo() {
		return this.ppeNo;
	}

	public void setPpeNo(String ppeNo) {
		this.ppeNo = ppeNo;
	}

	@Column(name = "PPE_NAME", length = 50)
	public String getPpeName() {
		return this.ppeName;
	}

	public void setPpeName(String ppeName) {
		this.ppeName = ppeName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APP_DATE", length = 10)
	@DateTimeFormat(pattern="yyyy-MM-dd")
	public Date getAppDate() {
		return this.appDate;
	}

	public void setAppDate(Date appDate) {
		this.appDate = appDate;
	}

	@Column(name = "USED_RESON", length = 200)
	public String getUsedReson() {
		return this.usedReson;
	}

	public void setUsedReson(String usedReson) {
		this.usedReson = usedReson;
	}

	@Column(name = "REVERTER")
	public Integer getReverter() {
		return this.reverter;
	}

	public void setReverter(Integer reverter) {
		this.reverter = reverter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GIVEBACK_DATE", length = 10)
	public Date getGivebackDate() {
		return this.givebackDate;
	}

	public void setGivebackDate(Date givebackDate) {
		this.givebackDate = givebackDate;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
