package com.oasys.model;

// Generated 2015-12-10 13:43:04 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TOaAdVehicleExpensesApp generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_vehicle_expenses_app", uniqueConstraints = @UniqueConstraint(columnNames = "APP_NO"))
public class VehicleExpensesApp implements java.io.Serializable {

	private Integer veaId;
	private String appNo;
	private Integer applicantNo;
	private Integer deptNo;
	private Date appDate;
	private String appStatus;
	private String carNo;
	private String bankName;
	private String intoAct;
	private String actName;
	private Integer feeInfoId;
	private Character feeType;
	private String feeTypeOther;
	private Character procStatus;
	private String remark;

	public VehicleExpensesApp() {
	}

	public VehicleExpensesApp(String bankName, String intoAct,
			String actName) {
		this.bankName = bankName;
		this.intoAct = intoAct;
		this.actName = actName;
	}

	public VehicleExpensesApp(String appNo, Integer applicantNo,
			Integer deptNo, Date appDate, String appStatus, String carNo,
			String bankName, String intoAct, String actName, Integer feeInfoId,
			Character feeType, String feeTypeOther, Character procStatus,
			String remark) {
		this.appNo = appNo;
		this.applicantNo = applicantNo;
		this.deptNo = deptNo;
		this.appDate = appDate;
		this.appStatus = appStatus;
		this.carNo = carNo;
		this.bankName = bankName;
		this.intoAct = intoAct;
		this.actName = actName;
		this.feeInfoId = feeInfoId;
		this.feeType = feeType;
		this.feeTypeOther = feeTypeOther;
		this.procStatus = procStatus;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "VEA_ID", unique = true, nullable = false)
	public Integer getVeaId() {
		return this.veaId;
	}

	public void setVeaId(Integer veaId) {
		this.veaId = veaId;
	}

	@Column(name = "APP_NO", unique = true, length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "APPLICANT_NO")
	public Integer getApplicantNo() {
		return this.applicantNo;
	}

	public void setApplicantNo(Integer applicantNo) {
		this.applicantNo = applicantNo;
	}

	@Column(name = "DEPT_NO")
	public Integer getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(Integer deptNo) {
		this.deptNo = deptNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APP_DATE", length = 10)
	public Date getAppDate() {
		return this.appDate;
	}

	public void setAppDate(Date appDate) {
		this.appDate = appDate;
	}

	@Column(name = "APP_STATUS", length = 100)
	public String getAppStatus() {
		return this.appStatus;
	}

	public void setAppStatus(String appStatus) {
		this.appStatus = appStatus;
	}

	@Column(name = "CAR_NO", length = 10)
	public String getCarNo() {
		return this.carNo;
	}

	public void setCarNo(String carNo) {
		this.carNo = carNo;
	}

	@Column(name = "BANK_NAME", nullable = false, length = 80)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "INTO_ACT", nullable = false, length = 25)
	public String getIntoAct() {
		return this.intoAct;
	}

	public void setIntoAct(String intoAct) {
		this.intoAct = intoAct;
	}

	@Column(name = "ACT_NAME", nullable = false, length = 15)
	public String getActName() {
		return this.actName;
	}

	public void setActName(String actName) {
		this.actName = actName;
	}

	@Column(name = "FEE_INFO_ID")
	public Integer getFeeInfoId() {
		return this.feeInfoId;
	}

	public void setFeeInfoId(Integer feeInfoId) {
		this.feeInfoId = feeInfoId;
	}

	@Column(name = "FEE_TYPE", length = 1)
	public Character getFeeType() {
		return this.feeType;
	}

	public void setFeeType(Character feeType) {
		this.feeType = feeType;
	}

	@Column(name = "FEE_TYPE_OTHER", length = 50)
	public String getFeeTypeOther() {
		return this.feeTypeOther;
	}

	public void setFeeTypeOther(String feeTypeOther) {
		this.feeTypeOther = feeTypeOther;
	}

	@Column(name = "PROC_STATUS", length = 1)
	public Character getProcStatus() {
		return this.procStatus;
	}

	public void setProcStatus(Character procStatus) {
		this.procStatus = procStatus;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
