package com.bpms.model;

// Generated 2015-6-16 10:13:19 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * LoanorderAndCompany generated by hbm2java
 */
@Entity
@Table(name = "t_bp_loanorder_and_company")
public class LoanorderAndCompany implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	private String comId;
	private String loanOrderId;

	public LoanorderAndCompany() {
	}

	public LoanorderAndCompany(String id) {
		this.id = id;
	}

	public LoanorderAndCompany(String id, String comId, String loanOrderId) {
		super();
		this.id = id;
		this.comId = comId;
		this.loanOrderId = loanOrderId;
	}

	@Id
	@GenericGenerator(name = "systemUUID", strategy = "uuid")
	@GeneratedValue(generator = "systemUUID")
	@Column(name = "ID", insertable = true, updatable = true, nullable = false, length = 40, unique = true)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "COM_ID", length = 40)
	public String getComId() {
		return comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "LOAN_ORDER_ID", length = 40)
	public String getLoanOrderId() {
		return loanOrderId;
	}

	public void setLoanOrderId(String loanOrderId) {
		this.loanOrderId = loanOrderId;
	}

}
