/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-10-16 01:52:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.loanOrder.IPC;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class ipcMicrocreditOpinionAdd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var userData;\r\n");
      out.write("$(function(){\r\n");
      out.write("\t// 渲染姓名\r\n");
      out.write("\t$(\"#acceptTaskForm input[name='name']\").val($row.name);\r\n");
      out.write("\t// 渲染身份证号\r\n");
      out.write("\t$(\"#acceptTaskForm input[name='idNo']\").val($row.idNo);\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#attType\").combobox({\r\n");
      out.write("\t\tvalueField : 'code',\r\n");
      out.write("\t\ttextField : 'text',\r\n");
      out.write("\t\turl:'common/commonAction!findTextArr.action?codeMyid=attachment_type',\r\n");
      out.write("\t\tonLoadSuccess : function(){\r\n");
      out.write("\t\t\tvar val = $(this).combobox(\"getData\");\r\n");
      out.write("\t\t\tif(!$.isEmptyObject(val)){\r\n");
      out.write("                $(this).combobox(\"select\", val[0][\"code\"]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\teditable:false\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("   $(\"#microcreditOpinionDlg input[name='operatorA']\").combobox({\r\n");
      out.write("\t\tvalueField : 'code',\r\n");
      out.write("\t\ttextField : 'text',\r\n");
      out.write("\t\trequired:true,\r\n");
      out.write("\t\turl:'users/usersAction!findUsers.action',\r\n");
      out.write("\t\tonLoadSuccess : function(){\r\n");
      out.write("\t\t\tuserData = $(this).combobox(\"getData\");\r\n");
      out.write("\t\t\tfor (var item in userData[0]) {\r\n");
      out.write("                if (item == \"code\") {\r\n");
      out.write("                    $(this).combobox(\"select\", userData[0][item]);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\teditable:false ,\r\n");
      out.write("\t\tonSelect:function(record){\r\n");
      out.write("\t\t\t$(\"input[name='operatorAS']\").val(record.text);\r\n");
      out.write("\t\t},\r\n");
      out.write("    }); \r\n");
      out.write("   \r\n");
      out.write("\t   $(\"#microcreditOpinionDlg input[name='operatorB']\").combobox({\r\n");
      out.write("\t\t\tvalueField : 'code',\r\n");
      out.write("\t\t\ttextField : 'text',\r\n");
      out.write("\t\t\trequired:true,\r\n");
      out.write("\t\t\turl:'users/usersAction!findUsers.action',\r\n");
      out.write("\t\t\tonLoadSuccess : function(){\r\n");
      out.write("\t\t\t\tvar val = $(this).combobox(\"getData\");\r\n");
      out.write("\t\t\t\tif(!$.isEmptyObject(val)){\r\n");
      out.write("\t\t\t\t\tuserData = val;\r\n");
      out.write("\t                $(this).combobox(\"select\", val[0][\"code\"]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\teditable:false ,\r\n");
      out.write("\t\t\tonSelect:function(record){\r\n");
      out.write("\t\t\t\t$(\"input[name='operatorBS']\").val(record.text);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t   }); \r\n");
      out.write("\t\r\n");
      out.write("\t//还款期限\r\n");
      out.write("\t$(\"#microcreditOpinionDlg input[name='adviceLoanPeriod']\").combobox({\r\n");
      out.write("\t\tvalueField : 'code',\r\n");
      out.write("\t\ttextField : 'text',\r\n");
      out.write("\t\trequired:true,\r\n");
      out.write("\t\turl:'common/commonAction!findTextArr.action?codeMyid=loan_period_type',\r\n");
      out.write("\t\teditable:false ,\r\n");
      out.write("\t\tonLoadSuccess : function(){\r\n");
      out.write("\t\t\tvar val = $(this).combobox(\"getData\");\r\n");
      out.write("\t\t\tif(!$.isEmptyObject(val)){\r\n");
      out.write("\t\t\t\t//userData = val;\r\n");
      out.write("                $(this).combobox(\"select\", val[0][\"code\"]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\t// 信贷方式\r\n");
      out.write("   $(\"input[name='auditWay']\").combobox({\r\n");
      out.write("\t\twidth:171,\r\n");
      out.write("\t\turl:\"common/commonAction!findTextArr.action?codeMyid=audit_way\",\r\n");
      out.write("\t\tvalueField: 'code',\r\n");
      out.write("\t\ttextField: 'text',\r\n");
      out.write("\t\tonLoadSuccess : function(){\r\n");
      out.write("        \tvar val = $(this).combobox(\"getData\");\r\n");
      out.write("\t\t\tif(!$.isEmptyObject(val)){\r\n");
      out.write("              \t$(this).combobox(\"select\", val[0][\"code\"]);\r\n");
      out.write("            }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t// 微带呈报意见表信息\r\n");
      out.write("\tloadData();\r\n");
      out.write("})\r\n");
      out.write("\n");
      out.write("//查询系统参数\r\n");
      out.write("function checkSysParameter(paramCode){\r\n");
      out.write("\tvar datas = \"\";\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"sysParameter/sysParameterAction!findSysParameter.action\",\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tdata:{\"parmCode\":paramCode},\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tdatas = data.parmValue;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\treturn datas;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 保存微保意见\r\n");
      out.write("function saveMicrocreditOpinion(formId,dlgId){\r\n");
      out.write("\tvar isCheck = false;\r\n");
      out.write("\t$(\"#checkBoxDiv input[type='checkbox']\").each(function() {\r\n");
      out.write("\t\tif($(this).attr(\"checked\")){\r\n");
      out.write("\t\t\tisCheck = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tif(isCheck==false){\r\n");
      out.write("\t\t$.messager.alert(\"提示\",\"至少选择一条风险控制措施\",\"info\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t// 确认是否提交\r\n");
      out.write("\t$.messager.confirm('提示', '点击按钮之后将进入下一个任务活动环节,此任务将对您不可见!', function(r){\r\n");
      out.write("\t\tif (r){\r\n");
      out.write("\t\t\t$(\"#\"+formId).form('submit', {\r\n");
      out.write("\t\t\t\turl : \"microcreditOpinion/microcreditOpinionAction!saveMicrocreditOpinion.action\",\r\n");
      out.write("\t\t\t\tonSubmit : function(param) {\r\n");
      out.write("\t\t\t\t\tvar isValid = $(\"#\"+formId).form('validate');\r\n");
      out.write("\t\t\t\t\treturn isValid; // 返回false终止表单提交\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tdata = $.parseJSON(data);\r\n");
      out.write("\t\t\t\t\t$(\"#\"+formId+\" input[name='mcbrId']\").val(data.data);\r\n");
      out.write("\t\t\t\t\tsubmitTask(\"IPCCensorThrough\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 获取微贷承包意见表的信息\r\n");
      out.write("function loadData(){\r\n");
      out.write("\t$(\"#microcreditOpinionForm\").form(\"clear\");\r\n");
      out.write("\t//加载微贷业务表\r\n");
      out.write("\t$(\"#microcreditOpinionForm\").form(\"load\",\"microcreditOpinion/microcreditOpinionAction!findMicrocreditOpinionByOid.action?loanOrderId=\"+$row.loanOrderId);\r\n");
      out.write("\t$(\"#microcreditOpinionForm :input\").removeAttr(\"disabled\");\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#microcreditOpinionForm input[name='adviceLoanAmt']\").val(\"\");\r\n");
      out.write("\t// 组织机构的信息--进件城市\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"POST\",\r\n");
      out.write("\t\turl : \"loanOrder/loanOrderAction!findLoanCityByOrderId.action\",\r\n");
      out.write("\t\tdata : {\"loanOrderId\":$row.loanOrderId},\r\n");
      out.write("\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\tif(data){\r\n");
      out.write("\t\t\t\t$(\"#microcreditOpinionDlg input[name='loanCtiy']\").val(\"IPC项目组-\"+data.fullName);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#microcreditOpinionDlg input[name='name']\").val($row.name);\r\n");
      out.write("\t$(\"#microcreditOpinionDlg input[name='loanOrderId']\").val($row.loanOrderId);\r\n");
      out.write("\t$(\"#microcreditOpinionDlg input[name='idNo']\").val($row.idNo);\r\n");
      out.write("\t$(\"#microcreditOpinionDlg input[name='purpose']\").val($row.purpose);\r\n");
      out.write("\t$(\"#microcreditOpinionDlg input[name='adviceLoanAmt']\").val($row.loanAmount);\r\n");
      out.write("\t//checkSysParameter\r\n");
      out.write("\t$(\"#microcreditOpinionDlg input[name='loanMthd']\").val(checkSysParameter('loan_mthd'));\r\n");
      out.write("\t$(\"#microcreditOpinionDlg input[name='adviceRepayMthd']\").val(checkSysParameter('repay_mthd'));\r\n");
      out.write("\t$(\"#microcreditOpinionDlg input[name='loanRate']\").val(checkSysParameter('loan_rate'));\r\n");
      out.write("\t$(\"#microcreditOpinionDlg input[name='counselingRate']\").val(checkSysParameter('counseling_rate'));\r\n");
      out.write("\t$(\"#microcreditOpinionDlg input[name='collectionMthd']\").val(checkSysParameter('collection_mthd'));\r\n");
      out.write("\t\r\n");
      out.write("\t// 设置办理人\r\n");
      out.write("\t$(\"input[name='operatorAS']\").val($(\"#operatorA\").combobox('getText'));\r\n");
      out.write("\t$(\"input[name='operatorBS']\").val($(\"#operatorB\").combobox('getText'));\r\n");
      out.write("\t//根据订单ID 共同贷款人 名称 ID\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"loanerJoint/loanerJointAction!findLoanerJointByOrderId.action\",\r\n");
      out.write("\t\tdata : {\r\n");
      out.write("\t\t\tloanOrderId : $row.loanOrderId\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tasync: false,\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\tif(data){\r\n");
      out.write("\t\t\t\t$(\"#microcreditOpinionDlg input[name='coborrowerName']\").val(data.name);\r\n");
      out.write("\t\t\t\t$(\"#microcreditOpinionDlg input[name='coborrowerIdno']\").val(data.idNo);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("</script>\r\n");
      out.write("<!-- 微贷业务呈报意见表E -->\t\t\r\n");
      out.write("<div id=\"microcreditOpinionDlg\">\r\n");
      out.write("\t<form id=\"microcreditOpinionForm\" method=\"post\">\r\n");
      out.write("\t\t<input name=\"mcbrId\" type=\"hidden\" />\r\n");
      out.write("\t\t<div style=\"text-align:center;\">\r\n");
      out.write("\t\t\t<font size=\"4\" style=\"font-weight: bold;\">微贷业务呈报意见表</font>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<table cellpadding=\"8px;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t借款人\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" name=\"name\"  type=\"text\" />\r\n");
      out.write("\t\t\t\t\t\t<input name=\"loanOrderId\" type=\"hidden\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t身份证号\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" name=\"idNo\"  type=\"text\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t贷款用途\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" name=\"purpose\"  type=\"text\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t共同借款人\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" name=\"coborrowerName\"  type=\"text\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t身份证号\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" data-options=\"validType:'idcard'\" name=\"coborrowerIdno\"  type=\"text\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t利率(年)\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" name=\"loanRate\"  type=\"text\" />%\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t放款方式\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" name=\"loanMthd\"  type=\"text\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t收取方式\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" name=\"collectionMthd\"  type=\"text\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t还款方式\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" name=\"adviceRepayMthd\"  type=\"text\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t咨询服务费\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" name=\"counselingRate\"  type=\"text\" />%\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t经办机构/部门\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td><input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" name=\"loanCtiy\"  type=\"text\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t建议金额(元)\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"easyui-validatebox easyui-textbox\" data-options=\"validType:'mDouble',required:true\" name=\"adviceLoanAmt\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t期限(月)\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"easyui-validatebox easyui-textbox easyui-combobox\" name=\"adviceLoanPeriod\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>信贷方式:</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"auditWay\" class=\"easyui-combobox\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t经办人\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\tA:<input id=\"operatorA\" class=\"easyui-validatebox easyui-textbox easyui-combobox\" name=\"operatorA\"  />&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\tB:<input id=\"operatorB\" class=\"easyui-validatebox easyui-textbox easyui-combobox\" name=\"operatorB\" /> \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div style=\"width:99.5%;height:270px;\">\r\n");
      out.write("\t\t\t\t<div id=\"checkBoxDiv\" style=\"padding-left:10px;height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t<span style=\"font-weight:bold;\">风险控制措施:&nbsp;&nbsp;&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"checkbox\" id=\"chedixinyong\" type=\"checkbox\" name=\"riskCtrlMeasures\" checked=\"checked\" value=\"车抵+信用\" /><label for=\"chedixinyong\">车抵+信用</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"checkbox\" id=\"xinyong\" type=\"checkbox\" name=\"riskCtrlMeasures\" value=\"信用\" /><label for=\"xinyong\">信用</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"checkbox\" id=\"zejiafengxiancuoshi\" type=\"checkbox\" name=\"riskCtrlMeasures\" value=\"增加风控措施\" /><label for=\"zejiafengxiancuoshi\">增加风控措施</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"checkbox\" id=\"qita\" type=\"checkbox\" name=\"riskCtrlMeasures\" value=\"其他\" /><label for=\"qita\">其他</label>\r\n");
      out.write("\t\t\t\t\t\t<span style=\"padding-left:20px;font-weight:bold;\">具体措施如下:</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"height:230px;overflow:auto;\">\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"easyui-validatebox easyui-textbox\" data-options=\"required:true\" name=\"specificMeasures\" style=\"width:99%;height:220px;resize: none;\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<table cellpadding=\"8px;\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th rowspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t业务经办人\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" name=\"operatorAS\" type=\"text\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<th rowspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t后台人员\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t初次上会\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"easyui-validatebox easyui-textbox\" name=\"firstMeeting\" type=\"text\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<th rowspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t部门负责人\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"easyui-validatebox easyui-textbox\" name=\"deptPrincipal\" data-options=\"required:true\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4;\" class=\"easyui-validatebox easyui-textbox\" name=\"operatorBS\" type=\"text\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t补调核实\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"easyui-validatebox easyui-textbox\" name=\"verification\" type=\"text\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div id=\"upload_form\" style=\"width: 100%; height: 30px; text-align: right;\">\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"saveMicrocreditOpinion('microcreditOpinionForm');\">提交</a>\r\n");
      out.write("\t</div> \r\n");
      out.write("</div>\r\n");
      out.write("<!-- 微贷业务呈报意见表E -->\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
