/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2016-01-27 06:08:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.loanOrder.IPC;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class ipcMicrocreditOpinionRefuseSuggestionAdd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t  \r\n");
      out.write("\t   $(\"#microcreditOpinionRefuseDlg input[name='operatorA']\").combobox({\r\n");
      out.write("\t\t\tvalueField : 'code',\r\n");
      out.write("\t\t\ttextField : 'text',\r\n");
      out.write("\t\t\trequired:true,\r\n");
      out.write("\t\t\turl:'users/usersAction!findUsers.action',\r\n");
      out.write("\t\t\teditable:false ,\r\n");
      out.write("\t\t\tonSelect:function(record){\r\n");
      out.write("\t\t\t\t$(\"input[name='operatorAR']\").val(record.text);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t  }); \r\n");
      out.write("\t   \r\n");
      out.write("\t   $(\"#microcreditOpinionRefuseDlg input[name='operatorB']\").combobox({\r\n");
      out.write("\t\t\tvalueField : 'code',\r\n");
      out.write("\t\t\ttextField : 'text',\r\n");
      out.write("\t\t\trequired:true,\r\n");
      out.write("\t\t\turl:'users/usersAction!findUsers.action',\r\n");
      out.write("\t\t\teditable:false ,\r\n");
      out.write("\t\t\tmultiple:true,\r\n");
      out.write("\t\t\twidth:250,\r\n");
      out.write("\t\t\tonSelect:function(record){\r\n");
      out.write("\t\t\t\t$(\"input[name='operatorBR']\").val(record.text);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t  }); \r\n");
      out.write("\t  \r\n");
      out.write("\t//加载拒绝决议表   \r\n");
      out.write("    $.ajax({\r\n");
      out.write("\t\turl : \"microcreditOpinion/microcreditOpinionAction!findMicrocreditOpinionByOid.action\",\r\n");
      out.write("\t\tdata : {\"loanOrderId\":$row.loanOrderId},\r\n");
      out.write("\t\ttype : \"POST\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\tif(data){\r\n");
      out.write("\t\t\t\tdata.operatorB = data.operatorB.replace(/\\s/g,\"\").split(\",\");\r\n");
      out.write("\t\t\t\t$(\"#microcreditOpinionRefuseForm\").form(\"load\",data);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});   \r\n");
      out.write("\t   \r\n");
      out.write("\t//加载拒绝决议表\r\n");
      out.write("\t//$(\"#microcreditOpinionRefuseForm\").form(\"load\",\"microcreditOpinion/microcreditOpinionAction!findMicrocreditOpinionByOid.action?loanOrderId=\"+$row.loanOrderId);\r\n");
      out.write("\t// 组织机构的信息--进件城市\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"POST\",\r\n");
      out.write("\t\turl : \"loanOrder/loanOrderAction!findLoanCityByOrderId.action\",\r\n");
      out.write("\t\tdata : {\"loanOrderId\":$row.loanOrderId},\r\n");
      out.write("\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\tif(data){\r\n");
      out.write("\t\t\t\t$(\"#microcreditOpinionRefuseDlg input[name='loanCtiy']\").val(data.fullName);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t// 渲染审查评议表其他的属性值\r\n");
      out.write("\t$(\"#microcreditOpinionRefuseDlg input[name='name']\").val($row.name);\r\n");
      out.write("\t$(\"#microcreditOpinionRefuseDlg input[name='loanOrderId']\").val($row.loanOrderId);\r\n");
      out.write("\t$(\"#microcreditOpinionRefuseDlg input[name='idNo']\").val($row.idNo);\r\n");
      out.write("\t$(\"#microcreditOpinionRefuseDlg input[name='purpose']\").val($row.purpose);\r\n");
      out.write("\t$(\"#microcreditOpinionRefuseDlg input[name='loanAmount']\").numberbox({value:$row.loanAmount,});\r\n");
      out.write("\tsetTimeout(\"loadOperator()\",300);\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function loadOperator() {\r\n");
      out.write("\t$(\"#microcreditOpinionRefuseDlg input[name='operatorAR']\").val($(\"#operatorAR\").combobox('getText'));\r\n");
      out.write("\t$(\"#microcreditOpinionRefuseDlg input[name='operatorBR']\").val($(\"#operatorBR\").combobox('getText'));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 保存微保意见\r\n");
      out.write("function saveMicrocreditOpinion(formId){\r\n");
      out.write("\t// 确认是否提交\r\n");
      out.write("\t$.messager.confirm('提示', '点击按钮之后将进入下一个任务活动环节,此任务将对您不可见!', function(r){\r\n");
      out.write("\t\tif (r){\r\n");
      out.write("\t\t\t$(\"#\"+formId).form('submit', {\r\n");
      out.write("\t\t\t\turl : \"microcreditOpinion/microcreditOpinionAction!saveMicrocreditOpinion.action\",\r\n");
      out.write("\t\t\t\tonSubmit : function(param) {\r\n");
      out.write("\t\t\t\t\tvar isValid = $(\"#\"+formId).form('validate');\r\n");
      out.write("\t\t\t\t\treturn isValid; // 返回false终止表单提交\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tdata = $.parseJSON(data);\r\n");
      out.write("\t\t\t\t\t$(\"#\"+formId+\" input[name='mcbrId']\").val(data.data);\r\n");
      out.write("\t\t\t\t\tsubmitTask(\"IPCCensorReject\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("</script>\r\n");
      out.write("<!-- 拒绝决议表S -->\r\n");
      out.write("<div id=\"microcreditOpinionRefuseDlg\">\r\n");
      out.write("\t<form id=\"microcreditOpinionRefuseForm\" method=\"post\"> \r\n");
      out.write("\t\t<input name=\"mcbrId\" type=\"hidden\" />\r\n");
      out.write("\t\t<div style=\"text-align:center;\">\r\n");
      out.write("\t\t\t<font size=\"4\" style=\"font-weight: bold;\">拒绝决议表</font>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<table cellpadding=\"5\" style=\"width:100%;height:100%;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t客户姓名\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"name\" class=\"easyui-textbox\" readonly=\"readonly\" style=\"background-color: #EBEBE4\" type=\"text\" value=\"韩冰\"/>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"loanOrderId\" type=\"hidden\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t身份证号\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td >\r\n");
      out.write("\t\t\t\t\t\t<input readonly=\"readonly\" style=\"background-color: #EBEBE4\" style=\"background-color: #EBEBE4\" class=\"easyui-validatebox easyui-textbox\" name=\"idNo\"  type=\"text\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t申请金额(元)\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"loanAmount\" readonly=\"readonly\" style=\"background-color: #EBEBE4\" class=\"easyui-validatebox easyui-numberbox\" data-options=\"precision:2,groupSeparator:','\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t贷款目的\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"purpose\"  readonly=\"readonly\" style=\"background-color: #EBEBE4\" class=\"easyui-validatebox easyui-textbox\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t调查日期\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td >\r\n");
      out.write("\t\t\t\t\t\t<input id=\"surveyDate\" name=\"surveyDate\" class=\"easyui-textbox easyui-datebox\" data-options=\"editable:false\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t所在地区\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td><input readonly=\"readonly\" style=\"background-color: #EBEBE4\" class=\"easyui-validatebox easyui-textbox\" name=\"loanCtiy\"  type=\"text\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t调查人员\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"5\">\r\n");
      out.write("\t\t\t\t\t\tA:<input id=\"operatorAR\" name=\"operatorA\" />&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\tB:<input id=\"operatorBR\" name=\"operatorB\"  /> \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>拒绝原因:</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"6\">\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"easyui-validatebox easyui-textbox\" data-options=\"required:true,validType:'length[0,1024]'\" name=\"rejectCause\" style=\"width:99%;height:320px;resize: none;\"></textarea>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"6\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"upload_form\" style=\"width: 100%; height: 30px; text-align: right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"saveMicrocreditOpinion('microcreditOpinionRefuseForm');\">提交</a>\r\n");
      out.write("\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\t\r\n");
      out.write(" </div>\r\n");
      out.write("<!-- 决绝决议表E -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
