/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2016-01-27 05:27:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.loanOrder.settlement;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bpms.util.Constants;
import com.bpms.shiro.ShiroUser;
import java.util.*;

public final class relativeWrodInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

 ShiroUser shiroUser = Constants.getCurrendUser();

      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("    \t\turl:\"loanContract/loanContractAction!findLoanContractRelativeInfo.action\",\r\n");
      out.write("    \t\ttype:\"post\",\r\n");
      out.write("    \t\tdata:{\"loanOrderId\":$row.loanOrderId},\r\n");
      out.write("    \t\tsuccess:function(data){\r\n");
      out.write("    \t\t\tif(data.status){\r\n");
      out.write("    \t\t\t\t$(\"#contractDetailForm\").form(\"load\",data.data);\r\n");
      out.write("    \t\t\t}else{\r\n");
      out.write("    \t\t\t\t$.messager.alert('提示',data.message,'error');\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\turl : \"loanContract/loanContractAction!findBankAccountInfo.action\",\r\n");
      out.write("\t\t\tdata : {\"loanOrderId\":$row.loanOrderId},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tif (data) {\r\n");
      out.write("\t\t\t\t\tvar htmlC = \"\";\r\n");
      out.write("\t\t\t\t\t$.each(data,function(i,item) {\r\n");
      out.write("\t\t\t\t\t\tif (item.primaryBackup==\"A\") {\r\n");
      out.write("\t\t\t\t\t\t\thtmlC += \"<tr><th>主卡</th></tr>\";\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\thtmlC += \"<tr><th>副卡</th></tr>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\thtmlC += \"<tr><th>开户银行全称</th>\";\r\n");
      out.write("\t\t\t\t\t\thtmlC += \"<td><input name='bankNames' class='easyui-textbox' disabled='disabled' value='\"+item.bankName+\"'/></td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlC += \"<th>开户行户名</th>\";\r\n");
      out.write("\t\t\t\t\t\thtmlC += \"<td><input name='accountNames' class='easyui-textbox' disabled='disabled' value='\"+item.accountName+\"'/></td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlC += \"<th>开户行账号</th>\";\r\n");
      out.write("\t\t\t\t\t\thtmlC += \"<td><input name='accountNums' class='easyui-textbox' disabled='disabled' value='\"+item.accountNum+\"'/></td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlC += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#contractDetailForm table\").append(htmlC);\r\n");
      out.write("\t\t\t\t\t$.parser.parse($(\"#contractDetailForm\"));\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#contractDetailForm input\").attr(\"disabled\",\"disabled\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction saveBankInfo() {\r\n");
      out.write("\t\t$(\"#contractDetailForm\").form('submit', {\r\n");
      out.write("\t\t\turl : \"loanContract/loanContractAction!modifyBankInfo.action\",\r\n");
      out.write("\t\t\tonSubmit : function(param) {\r\n");
      out.write("\t\t\t\tvar isValid = $(this).form('validate');\r\n");
      out.write("\t\t\t\treturn isValid; // 返回false终止表单提交\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tdata = $.parseJSON(data);\r\n");
      out.write("\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\ttitle:\"提示\",\r\n");
      out.write("\t\t\t\t\tmsg:data.message,\r\n");
      out.write("\t\t\t\t\tshowType:\"slide\",\r\n");
      out.write("\t\t\t\t\ttimeout:1000\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<div >\r\n");
      out.write("\t<form id=\"contractDetailForm\" method=\"post\">\r\n");
      out.write("\t\t\t<input name=\"lcId\" type=\"hidden\">\r\n");
      out.write("\t\t\t<table cellpadding=\"8px;\" style=\"width:100%;height:100%;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>姓名</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"loaner\" class=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t\t<th>身份证号</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"loanerIdno\" class=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t\t<th>贷款额度(元)</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"loanEdu\" class=\"easyui-numberbox\" data-options=\"precision:2,groupSeparator:','\"  /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>联系电话</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"loanerTel\" class=\"easyui-textbox\"  /></td>\r\n");
      out.write("\t\t\t\t\t<th>签字日期</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"loanerSignDate\" class=\"easyui-textbox\"  /></td>\r\n");
      out.write("\t\t\t\t\t<th>贷款期数</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"loanPeriods\" class=\"easyui-textbox\"  /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>出借人</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"lender\" class=\"easyui-textbox\"  /></td>\r\n");
      out.write("\t\t\t\t\t<th>出借人身份证号</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"lenderIdno\" class=\"easyui-textbox\"  /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>贷款用途</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"purpose\" class=\"easyui-textbox\"  /></td>\r\n");
      out.write("\t\t\t\t\t<th>通讯地址</th>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\"><input name=\"loanerPostalAddr\" class=\"easyui-textbox\"  style=\"width:100%;\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>月利率</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"monthlyRate\" class=\"easyui-textbox\"  /></td>\r\n");
      out.write("\t\t\t\t\t<th>贷款利息(元)</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"loanInterest\" class=\"easyui-numberbox\" data-options=\"precision:2,groupSeparator:','\" /></td>\r\n");
      out.write("\t\t\t\t\t<th>月还款额度(元)</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"monthlyRepayment\" class=\"easyui-numberbox\" data-options=\"precision:2,groupSeparator:','\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- <tr>\r\n");
      out.write("\t\t\t\t\t<th>贷款人开户银行全称</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"loanerBankName\" class=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t\t<th>贷款人开户行户名</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"loanerActName\" class=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t\t<th>贷款人开户行账号</th>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"loanerActNum\" class=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr> -->\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t<!-- <div title=\"还款管理服务说明书\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div title=\"借款协议\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div title=\"上海资信授权书\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div title=\"委托划款授权书\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div title=\"信用咨询及管理服务协议\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div> -->\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
