/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-12-22 07:50:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.investorReport;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class investorSummaryStatement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"  \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <title>客户详情汇总</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../layout/script.jsp", out, false);
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#customerRepaymentDetailForm input{\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var $lcid;\r\n");
      out.write("$(function(){\r\n");
      out.write("\t// 查看申请状态\r\n");
      out.write("\t$datagrid = $(\"#investorRelativeTab\").datagrid({\r\n");
      out.write("\t\turl : \"investorRelativeTabsExport/investorRelativeTabsExportAciton!queryInvestorSummaryStatement.action\",\r\n");
      out.write("\t\twidth : 'auto',\r\n");
      out.write("\t\theight : parseInt($(this).height()*0.79),\r\n");
      out.write("\t\tpagination:true,\r\n");
      out.write("\t\trownumbers:true,\r\n");
      out.write("\t\tborder:true,\r\n");
      out.write("\t\tsingleSelect:true,\r\n");
      out.write("\t\tnowrap:true,\r\n");
      out.write("\t\tmultiSort:false,\r\n");
      out.write("\t\tcolumns : [ [ \r\n");
      out.write("\t\t              {field : 'contractNo',title : '合同序号',width :100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'name',title : '客户姓名',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'idNo',title : '身份证号码',width : 150,align : 'center'},\r\n");
      out.write("\t\t              {field : 'mobilePhone',title : '联系方式',width : 120,align : 'center'},\r\n");
      out.write("\t\t              {field : 'address',title : '家庭住址',width : 200,align : 'center'},\r\n");
      out.write("\t\t              {field : 'zipCode',title : '邮编',width : 70,align : 'center'},\r\n");
      out.write("\t\t              {field : 'email',title : '邮箱',width : 170,align : 'center'},\r\n");
      out.write("\t\t              {field : 'bankName',title : '划扣银行',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'cardNo',title : '银行卡号',width : 120,align : 'center'},\r\n");
      out.write("\t\t              {field : 'transferPlatform',title : '划扣平台',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'investAmt',title : '理财金额',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'yearAmt',title : '年化金额',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'productName',title : '产品名称',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'ars',title : '年化收益率(%)',width : 90,align : 'center'},\r\n");
      out.write("\t\t              {field : 'interestDate',title : '计息日期',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'dueDate',title : '到期日期',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'pstatus',title : '状态',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'repaymentMethod',title : '还款方式',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'interestAmt',title : '利息总额',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'interestPayable',title : '应付利息',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'amtPayable',title : '应付金额',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'montyInterest',title : '月付利息',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'transferDate',title : '划扣日期',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'financialAdvisor',title : '理财顾问',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'teamManager',title : '团队经理',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'groupManager',title : '大团经理',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'businessDepartment',title : '营业部',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'cusNo',title : '客户编号',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'sendWay',title : '派送方式',width : 150,align : 'center'},\r\n");
      out.write("\t\t              {field : 'remark',title : '备注',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'isPay',title : '是否付息',width : 100,align : 'center'},\r\n");
      out.write("\t\t              ] ]\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#transferPlatform\").combobox({\r\n");
      out.write("\t\teditable:false,\r\n");
      out.write("\t\tvalueField: 'label',\r\n");
      out.write("\t\ttextField: 'value',\r\n");
      out.write("\t\tdata:[{label:'1',value:'富友'},{label:'2',value:'好易联'}]\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#repaymentMethod\").combobox({\r\n");
      out.write("\t\tvalueField : 'code',\r\n");
      out.write("\t\ttextField : 'text',\r\n");
      out.write("\t\turl:\"common/commonAction!findTextArr.action?codeMyid=repayment_mode\",\r\n");
      out.write("\t\teditable:false,\r\n");
      out.write("\t\tmethod:\"get\"\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#pstatus\").combobox({\r\n");
      out.write("\t\tvalueField : 'code',\r\n");
      out.write("\t\ttextField : 'text',\r\n");
      out.write("\t\turl:\"common/commonAction!findTextArr.action?codeMyid=prod_status\",\r\n");
      out.write("\t\teditable:false,\r\n");
      out.write("\t\tmethod:\"get\"\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#businessDepartment\").combobox({\r\n");
      out.write("\t\tvalueField : 'code',\r\n");
      out.write("\t\ttextField : 'text',\r\n");
      out.write("\t\turl:\"orgz/organizationAction!findOrganizationDept.action?treeLevel=05\",\r\n");
      out.write("\t\tmethod:\"get\",\r\n");
      out.write("\t\tfilter: function(q, row){\r\n");
      out.write("\t\t\tvar opts = $(this).combobox('options');\r\n");
      out.write("\t\t\treturn row[opts.textField].indexOf(q) != -1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#productName').combobox({\r\n");
      out.write("\t\tvalueField : 'code',\r\n");
      out.write("\t\ttextField : 'text',\r\n");
      out.write("\t    url:'investProduct/investProductAction!getAllProductCombobox.action',\r\n");
      out.write("\t    method:\"get\",\r\n");
      out.write("\t    filter: function(q, row){\r\n");
      out.write("\t\t\tvar opts = $(this).combobox('options');\r\n");
      out.write("\t\t\treturn row[opts.textField].indexOf(q) != -1;\r\n");
      out.write("\t\t}\r\n");
      out.write("    });   \r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//重置查询表单\r\n");
      out.write("function resetCustomerRepaymentForm(){\r\n");
      out.write("\t$(\"#investorRelativeForm\").form(\"clear\");\r\n");
      out.write("\t$(\"#investorRelativeTab\").datagrid('load',{});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//执行查询\r\n");
      out.write("function executeQuery(){\r\n");
      out.write("\t$(\"#investorRelativeTab\").datagrid('load',{\r\n");
      out.write("\t\t\t\"name\":$(\"#name\").val(),\r\n");
      out.write("\t\t\t\"transferPlatform\" :$(\"#transferPlatform\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"bankName\":$(\"#bankName\").val(),\r\n");
      out.write("\t\t\t\"productName\":$(\"#productName\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"transferDateStart\":$(\"#transferDateStart\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"transferDateEnd\":$(\"#transferDateEnd\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"dueDateStart\":$(\"#dueDateStart\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"dueDateEnd\":$(\"#dueDateEnd\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"repaymentMethod\":$(\"#repaymentMethod\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"mobilePhone\":$(\"#mobilePhone\").val(),\r\n");
      out.write("\t\t\t\"idNo\":$(\"#idNo\").val(),\r\n");
      out.write("\t\t\t\"email\":$(\"#email\").val(),\r\n");
      out.write("\t\t\t\"pstatus\":$(\"#pstatus\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"contractNo\":$(\"#contractNo\").val(),\r\n");
      out.write("\t\t\t\"cardNo\":$(\"#cardNo\").val(),\r\n");
      out.write("\t\t\t\"businessDepartment\":$(\"#businessDepartment\").combobox(\"getValue\")\r\n");
      out.write("\t\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 导出客户详情汇总\r\n");
      out.write("function exportInvestorRelativeTab(){\r\n");
      out.write("\tdownFileByFormPost(\"investorRelativeTabsExport/investorRelativeTabsExportAciton!exportInvestorSummaryStatement.action\",\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\"name\":$(\"#name\").val(),\r\n");
      out.write("\t\t\t\"transferPlatform\" :$(\"#transferPlatform\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"bankName\":$(\"#bankName\").val(),\r\n");
      out.write("\t\t\t\"productName\":$(\"#productName\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"transferDateStart\":$(\"#transferDateStart\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"transferDateEnd\":$(\"#transferDateEnd\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"dueDateStart\":$(\"#dueDateStart\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"dueDateEnd\":$(\"#dueDateEnd\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"repaymentMethod\":$(\"#repaymentMethod\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"mobilePhone\":$(\"#mobilePhone\").val(),\r\n");
      out.write("\t\t\t\"idNo\":$(\"#idNo\").val(),\r\n");
      out.write("\t\t\t\"email\":$(\"#email\").val(),\r\n");
      out.write("\t\t\t\"pstatus\":$(\"#pstatus\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"contractNo\":$(\"#contractNo\").val(),\r\n");
      out.write("\t\t\t\"cardNo\":$(\"#cardNo\").val(),\r\n");
      out.write("\t\t\t\"businessDepartment\":$(\"#businessDepartment\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"businessDepartmentName\":$(\"#businessDepartment\").combobox(\"getText\")\r\n");
      out.write("\t\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 导出理财支出预算\r\n");
      out.write("function exportInvestExpenditureBudget(){\r\n");
      out.write("\tdownFileByFormPost(\"investorRelativeTabsExport/investorRelativeTabsExportAciton!exportInvestExpenditureBudget.action\",\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\"name\":$(\"#name\").val(),\r\n");
      out.write("\t\t\t\"transferPlatform\" :$(\"#transferPlatform\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"bankName\":$(\"#bankName\").val(),\r\n");
      out.write("\t\t\t\"productName\":$(\"#productName\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"transferDateStart\":$(\"#transferDateStart\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"transferDateEnd\":$(\"#transferDateEnd\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"dueDateStart\":$(\"#dueDateStart\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"dueDateEnd\":$(\"#dueDateEnd\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"repaymentMethod\":$(\"#repaymentMethod\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"mobilePhone\":$(\"#mobilePhone\").val(),\r\n");
      out.write("\t\t\t\"idNo\":$(\"#idNo\").val(),\r\n");
      out.write("\t\t\t\"email\":$(\"#email\").val(),\r\n");
      out.write("\t\t\t\"pstatus\":$(\"#pstatus\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"contractNo\":$(\"#contractNo\").val(),\r\n");
      out.write("\t\t\t\"cardNo\":$(\"#cardNo\").val(),\r\n");
      out.write("\t\t\t\"businessDepartment\":$(\"#businessDepartment\").combobox(\"getValue\")\r\n");
      out.write("\t\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 导出临期兑付合同信息\r\n");
      out.write("function exportAdventOfPaymentContract(){\r\n");
      out.write("\tdownFileByFormPost(\"investorRelativeTabsExport/investorRelativeTabsExportAciton!exportAdventOfPaymentContract.action\",\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\"name\":$(\"#name\").val(),\r\n");
      out.write("\t\t\t\"transferPlatform\" :$(\"#transferPlatform\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"bankName\":$(\"#bankName\").val(),\r\n");
      out.write("\t\t\t\"productName\":$(\"#productName\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"transferDateStart\":$(\"#transferDateStart\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"transferDateEnd\":$(\"#transferDateEnd\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"dueDateStart\":$(\"#dueDateStart\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"dueDateEnd\":$(\"#dueDateEnd\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"repaymentMethod\":$(\"#repaymentMethod\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"mobilePhone\":$(\"#mobilePhone\").val(),\r\n");
      out.write("\t\t\t\"idNo\":$(\"#idNo\").val(),\r\n");
      out.write("\t\t\t\"email\":$(\"#email\").val(),\r\n");
      out.write("\t\t\t\"pstatus\":$(\"#pstatus\").combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\"contractNo\":$(\"#contractNo\").val(),\r\n");
      out.write("\t\t\t\"cardNo\":$(\"#cardNo\").val(),\r\n");
      out.write("\t\t\t\"businessDepartment\":$(\"#businessDepartment\").combobox(\"getValue\")\r\n");
      out.write("\t\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write(" </head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div style=\"padding-top:5px;\">\r\n");
      out.write("\t\t\t\t<font size=\"3em\">[查询条件]</font>\r\n");
      out.write("\t\t\t\t<form id=\"investorRelativeForm\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<table cellpadding=\"5px;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t客户姓名\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"name\" name=\"name\" class=\"easyui-textbox\" placeholder=\"请输入客户姓名\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t手机号\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"mobilePhone\" name=\"mobilePhone\" class=\"easyui-textbox\" placeholder=\"请输入手机号\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t身份证号\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"idNo\" name=\"idNo\" class=\"easyui-textbox\" placeholder=\"请输入身份证号\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t邮箱\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"email\" name=\"email\" class=\"easyui-textbox\" placeholder=\"请输入邮箱号\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t理财产品\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"productName\" name=\"productName\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t产品状态\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"pstatus\" name=\"pstatus\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t合同编号\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"contractNo\" name=\"contractNo\" class=\"easyui-textbox\" placeholder=\"请输入合同编号\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t银行卡号\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"cardNo\" name=\"cardNo\" class=\"easyui-textbox\" placeholder=\"请输入银行卡号\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t划扣银行\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"bankName\" name=\"bankName\" class=\"easyui-textbox\" placeholder=\"请输入银行名称\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t划扣平台\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"transferPlatform\" name=\"transferPlatform\"  />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t还款方式\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"repaymentMethod\" name=\"repaymentMethod\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t营业部门\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"businessDepartment\" name=\"businessDepartment\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t划扣日期\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"transferDateStart\" name=\"transferDateStart\" class=\"easyui-textbox easyui-datebox\" data-options=\"editable:false\" />\r\n");
      out.write("\t\t\t\t\t\t\t　　至　　\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"transferDateEnd\" name=\"transferDateEnd\" class=\"easyui-textbox easyui-datebox\" data-options=\"editable:false\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t到期日期\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"dueDateStart\" name=\"dueDateStart\" class=\"easyui-textbox easyui-datebox\" data-options=\"editable:false\" />\r\n");
      out.write("\t\t\t\t\t\t\t　　至　　\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"dueDateEnd\" name=\"dueDateEnd\" class=\"easyui-textbox easyui-datebox\" data-options=\"editable:false\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<div style=\"text-align:right;\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color:red;float:left;padding-top:6px;\">\r\n");
      out.write("\t\t\t\t\t\t注:不输入任何查询条件，默认查询所有客户详情\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"executeQuery();\">执行查询</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" iconCls=\"icon-reload\" onclick=\"resetCustomerRepaymentForm();\">重置条件</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" iconCls=\"icon-save\" onclick=\"exportInvestorRelativeTab();\">导出客户详情汇总</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" iconCls=\"icon-save\" onclick=\"exportInvestExpenditureBudget();\">导出理财支出预算</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" iconCls=\"icon-save\" onclick=\"exportAdventOfPaymentContract();\">导出临期兑付合同信息</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<table id=\"investorRelativeTab\" title=\"客户详情汇总\"></table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- 还款详情 -->\r\n");
      out.write("\t\t\t<div id=\"customerRepaymentDetailDlg\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<div style=\"height:120px;width:100%\">\r\n");
      out.write("\t\t\t\t<form id=\"customerRepaymentDetailForm\">\r\n");
      out.write("\t\t\t\t\t<table cellpadding=\"8px;\"> \r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>合同编号</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"contractNo\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>所属地区</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"organizationName\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>合同签署日期</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"contractSignDate\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>客户姓名</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"loanName\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>身份证号</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"loanIdNo\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>贷款类型</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"loanTypeName\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>贷款金额</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"loanEdu\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>贷款期数</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"loanPeriods\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>月还金额</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"monthlyRepayment\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>放款日期</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"loanBgDate\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>当前日期</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"now\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"height:520px;width:100%\">\r\n");
      out.write("\t\t\t\t<table id=\"customerRepaymentDetailTab\"></table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\t\t\t\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
