/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-12-14 09:54:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.investorReport;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class investExpenditureBudget_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"  \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <title>理财支出预算</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../layout/script.jsp", out, false);
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#customerRepaymentDetailForm input{\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var $lcid;\r\n");
      out.write("$(function(){\r\n");
      out.write("\t// 查看申请状态\r\n");
      out.write("\t$datagrid = $(\"#customerRepaymentTab\").datagrid({\r\n");
      out.write("\t\turl : \"loanCustRepaymentDetail/loanCustRepaymentDetailAction!findLoanCustRepaymentDetail.action\",\r\n");
      out.write("\t\twidth : 'auto',\r\n");
      out.write("\t\theight : parseInt($(this).height()*0.8),\r\n");
      out.write("\t\tpagination:true,\r\n");
      out.write("\t\trownumbers:true,\r\n");
      out.write("\t\tborder:true,\r\n");
      out.write("\t\tsingleSelect:true,\r\n");
      out.write("\t\tnowrap:true,\r\n");
      out.write("\t\tmultiSort:false,\r\n");
      out.write("\t\tcolumns : [ [ \r\n");
      out.write("\t\t              {field : 'contractNo',title : '合同编号',width :280,align : 'center',\r\n");
      out.write("\t\t\t            \tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t            \t\treturn \"<a href='javascript:void(0);' onclick='checkContractDetail(\"+index+\");'>\"+value+\"</a>　　\" ;\r\n");
      out.write("\t\t\t            \t}  \r\n");
      out.write("\t\t              },\r\n");
      out.write("\t\t              {field : 'loanName',title : '客户姓名',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'loanMobileTel',title : '联系方式',width : 120,align : 'center'},\r\n");
      out.write("\t\t              {field : 'loanerBankName',title : '划扣银行',width : 120,align : 'center'},\r\n");
      out.write("\t\t              {field : 'loanerActNum',title : '卡号',width : 150,align : 'center'},\r\n");
      out.write("\t\t              {field : 'loanBgDate',title : '理财金额',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'monthlyRepaymentDate',title : '理财产品',width : 60,align : 'center'},\r\n");
      out.write("\t\t              {field : 'repaymentBgDate',title : '本月计息天数',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'repaymentEndDate',title : '年化收益率',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'loanEdu',title : '利息总额',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'paidLoanPeriods',title : '应付金额',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'monthlyRepayment',title : '月付利息',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'now',title : '计息日期',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'loanPeriods',title : '到期日期',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'currentLoanPeriods',title : '营业部',width : 80,align : 'center'},\r\n");
      out.write("\t\t              ] ]\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//loadOrganization();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#isOverdue\").combobox({\r\n");
      out.write("\t\t\tvalueField: 'value',   \r\n");
      out.write("\t        textField: 'label',   \r\n");
      out.write("\t        data: [{\r\n");
      out.write("\t\t\t\tlabel: '全部',\r\n");
      out.write("\t\t\t\tvalue: '0'\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tlabel: '当期正常还款',\r\n");
      out.write("\t\t\t\tvalue: '1'\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tlabel: '逾期还款',\r\n");
      out.write("\t\t\t\tvalue: '2'\r\n");
      out.write("\t\t\t}],\r\n");
      out.write("\t\t\teditable:false ,\r\n");
      out.write("\t\t\tonLoadSuccess : function(){\r\n");
      out.write("\t\t\tuserData = $(this).combobox(\"getData\");\r\n");
      out.write("\t\t\tfor (var item in userData[0]) {\r\n");
      out.write("\t                if (item == \"value\") {\r\n");
      out.write("\t                    $(this).combobox(\"select\", userData[0][item]);\r\n");
      out.write("\t                }\r\n");
      out.write("\t            }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//重置查询表单\r\n");
      out.write("function resetCustomerRepaymentForm(){\r\n");
      out.write("\t$(\"#customerRepaymentForm\").form(\"clear\");\r\n");
      out.write("\t$(\"#customerRepaymentTab\").datagrid('load',{});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//执行查询\r\n");
      out.write("function subCustomerRepaymentForm(){\r\n");
      out.write("\t$(\"#customerRepaymentTab\").datagrid('load',{\r\n");
      out.write("\t\t\t\"contractNo\":$(\"#contractNo\").val(),\r\n");
      out.write("\t\t\t\"loanCity\" :$(\"#loanCity\").val(),\r\n");
      out.write("\t\t\t\"loanName\":$(\"#loanName\").val(),\r\n");
      out.write("\t\t\t\"planRepmtDate\":$(\"#planRepmtDate\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"contractSignDateS\":$(\"#contractSignDateS\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"contractSignDateE\":$(\"#contractSignDateE\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"isOverdue\":$(\"#isOverdue\").combobox(\"getValue\")\r\n");
      out.write("\t\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 导出逾期客户列表\r\n");
      out.write("function exportOverPeriodCustomerRepayment(){\r\n");
      out.write("\tdownFileByFormPost(\"loanCustRepaymentDetail/loanCustRepaymentDetailAction!exportLoanCustRepaymentDetail.action\",\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\"contractNo\":$(\"#contractNo\").val(),\r\n");
      out.write("\t\t\t\"loanCity\" :$(\"#loanCity\").val(),\r\n");
      out.write("\t\t\t\"loanName\":$(\"#loanName\").val(),\r\n");
      out.write("\t\t\t\"planRepmtDate\":$(\"#planRepmtDate\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"contractSignDateS\":$(\"#contractSignDateS\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"contractSignDateE\":$(\"#contractSignDateE\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"isOverdue\":'2'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//导出当期客户列表\r\n");
      out.write("function exportCurrentPeriodCustomerRepayment(){\r\n");
      out.write("\tdownFileByFormPost(\"loanCustRepaymentDetail/loanCustRepaymentDetailAction!exportLoanCustRepaymentDetail.action\",\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\"contractNo\":$(\"#contractNo\").val(),\r\n");
      out.write("\t\t\t\"loanCity\" :$(\"#loanCity\").val(),\r\n");
      out.write("\t\t\t\"loanName\":$(\"#loanName\").val(),\r\n");
      out.write("\t\t\t\"planRepmtDate\":$(\"#planRepmtDate\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"contractSignDateS\":$(\"#contractSignDateS\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"contractSignDateE\":$(\"#contractSignDateE\").datebox(\"getValue\"),\r\n");
      out.write("\t\t\t\"isOverdue\":'1'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//查看合同详情\r\n");
      out.write("function checkContractDetail(index){\r\n");
      out.write("\tvar rows = $(\"#customerRepaymentTab\").datagrid(\"getRows\");\r\n");
      out.write("\t$lcid = rows[index].lcid;\r\n");
      out.write("\t$(\"<div></div>\").dialog({\r\n");
      out.write("\t\ttitle:\"合同详情\",\r\n");
      out.write("\t\twidth: 1050,   \r\n");
      out.write("\t    height: 600,   \r\n");
      out.write("\t    closed: false,   \r\n");
      out.write("\t    cache: false,   \r\n");
      out.write("\t    closable:true,\r\n");
      out.write("\t    modal: true,\r\n");
      out.write("\t    href:\"jsp/loanerMonitoring/loanContractDetail.jsp\",\r\n");
      out.write("\t    onClose:function(){\r\n");
      out.write("\t    \t$(this).dialog(\"destroy\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//查询还款详情\r\n");
      out.write("function checkRepaymentDetail(index){\r\n");
      out.write("\tvar rows = $(\"#customerRepaymentTab\").datagrid(\"getRows\");\r\n");
      out.write("\tvar contractNo = rows[index].contractNo;\r\n");
      out.write("\t$(\"#customerRepaymentDetailDlg\").css(\"display\",\"block\").dialog({\r\n");
      out.write("\t\twidth:1150,\r\n");
      out.write("\t\theight:680,\r\n");
      out.write("\t\tclosed:false,\r\n");
      out.write("\t\tclosable:true,\r\n");
      out.write("\t\tmodal:true,\r\n");
      out.write("\t\ttitle:\"还款详情\",\r\n");
      out.write("\t\tonOpen:function(){\r\n");
      out.write("\t\t\t$(\"#customerRepaymentDetailForm\").form(\"load\",rows[index]);\r\n");
      out.write("\t\t\tloadCustomerRepaymentDetailTab(contractNo);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//加载客户还款信息详情列表\r\n");
      out.write("function loadCustomerRepaymentDetailTab(contractNo){\r\n");
      out.write("\t$(\"#customerRepaymentDetailTab\").datagrid({\r\n");
      out.write("\t\turl : \"loanCustRepaymentDetail/loanCustRepaymentDetailAction!findRepaymentDetailByCno.action\",\r\n");
      out.write("\t\twidth : 'auto',\r\n");
      out.write("\t\theight : 520,\r\n");
      out.write("\t\tpagination:true,\r\n");
      out.write("\t\trownumbers:false,\r\n");
      out.write("\t\tborder:true,\r\n");
      out.write("\t\tsingleSelect:true,\r\n");
      out.write("\t\tnowrap:true,\r\n");
      out.write("\t\tmultiSort:false,\r\n");
      out.write("\t\tqueryParams:{\"contractNo\":contractNo},\r\n");
      out.write("\t\tcolumns : [ [ \r\n");
      out.write("\t\t              {field : 'periods',title : '期数',width : 30,align : 'center'},\r\n");
      out.write("\t\t              {field : 'planRepmtDate',title : '应还款日期',width :100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'planRepmtAmt',title : '应还款金额(元)',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'realRepmtDate',title : '最后一次还款日期',width : 120,align : 'center'},\r\n");
      out.write("\t\t              {field : 'realRepmtAmt',title : '实际还款金额(元)',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'repmtAct',title : '还款账号',width : 120,align : 'center'},\r\n");
      out.write("\t\t              {field : 'overdueDays',title : '逾期天数(天)',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'lateFee',title : '滞纳金(元)',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'defaultInterest',title : '罚息(元)',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'freeInterestFee',title : '免息金额(元)',width : 100,align : 'center'},\r\n");
      out.write("\t\t              {field : 'rpmtStatusName',title : '还款状态',width : 80,align : 'center'},\r\n");
      out.write("\t\t              {field : 'operator',title : '操作人员',width : 80,align : 'center'}\r\n");
      out.write("\t\t              ] ]\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write(" </head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div style=\"margin-left: 5px;margin-top: 5px\">\r\n");
      out.write("\t\t\t\t业务管理-->财务监控管理-->贷款客户监管-->客户还款管理\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"padding-top:5px;\">\r\n");
      out.write("\t\t\t\t<font size=\"3em\">[查询条件]</font>\r\n");
      out.write("\t\t\t\t<form id=\"customerRepaymentForm\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<table cellpadding=\"10px;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t客户姓名\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"loanCity\" name=\"loanCity\" class=\"easyui-textbox\" placeholder=\"请输入进件地区\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t划扣平台\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"contractNo\" name=\"contractNo\" class=\"easyui-textbox\"  placeholder=\"请输入合同编号\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t划扣银行\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"loanName\" name=\"loanName\" class=\"easyui-textbox\" placeholder=\"请输入客户姓名\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t理财产品\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"planRepmtDate\" name=\"planRepmtDate\" class=\"easyui-textbox easyui-datebox\" data-options=\"editable:false\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t划扣日期\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"contractSignDateS\" name=\"contractSignDateS\" placeholder=\"请选择起始日期\" class=\"easyui-textbox easyui-datebox\" data-options=\"editable:false\" />\r\n");
      out.write("\t\t\t\t\t\t\t　　至　　\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"contractSignDateE\" name=\"contractSignDateE\" placeholder=\"请选择截止日期\" class=\"easyui-textbox easyui-datebox\" data-options=\"editable:false\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t到期日期\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"contractSignDateS\" name=\"contractSignDateS\" placeholder=\"请选择起始日期\" class=\"easyui-textbox easyui-datebox\" data-options=\"editable:false\" />\r\n");
      out.write("\t\t\t\t\t\t\t　　至　　\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"contractSignDateE\" name=\"contractSignDateE\" placeholder=\"请选择截止日期\" class=\"easyui-textbox easyui-datebox\" data-options=\"editable:false\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t还款方式（按月回息/利随本清）\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"planRepmtDate\" name=\"planRepmtDate\" class=\"easyui-textbox easyui-datebox\" data-options=\"editable:false\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<div style=\"text-align:right;\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color:red;float:left;padding-top:6px;\">\r\n");
      out.write("\t\t\t\t\t\t注:不输入任何查询条件，默认查询所有客户还款详情\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"subCustomerRepaymentForm();\">执行查询</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" iconCls=\"icon-reload\" onclick=\"resetCustomerRepaymentForm();\">重置条件</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" iconCls=\"icon-save\" onclick=\"exportOverPeriodCustomerRepayment();\">导出逾期客户还款明细</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" iconCls=\"icon-save\" onclick=\"exportCurrentPeriodCustomerRepayment();\">导出当期客户还款明细</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<table id=\"customerRepaymentTab\" title=\"客户还款管理\"></table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- 还款详情 -->\r\n");
      out.write("\t\t\t<div id=\"customerRepaymentDetailDlg\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<div style=\"height:120px;width:100%\">\r\n");
      out.write("\t\t\t\t<form id=\"customerRepaymentDetailForm\">\r\n");
      out.write("\t\t\t\t\t<table cellpadding=\"8px;\"> \r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>合同编号</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"contractNo\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>所属地区</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"organizationName\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>合同签署日期</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"contractSignDate\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>客户姓名</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"loanName\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>身份证号</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"loanIdNo\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>贷款类型</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"loanTypeName\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>贷款金额</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"loanEdu\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>贷款期数</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"loanPeriods\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>月还金额</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"monthlyRepayment\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>放款日期</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"loanBgDate\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>当前日期</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"now\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"height:520px;width:100%\">\r\n");
      out.write("\t\t\t\t<table id=\"customerRepaymentDetailTab\"></table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\t\t\t\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
