/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-12-08 01:18:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.loanOrder.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loanOrderWorkUnit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function initDatagrid(queryParams) {\r\n");
      out.write("\t$(\"#dwDatagrid\").datagrid({\r\n");
      out.write("\t\t\twidth : 863,\r\n");
      out.write("\t\t\theight : 370,\r\n");
      out.write("\t\t\tpagination : false,\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tborder : true,\r\n");
      out.write("\t\t\tsingleSelect : false,\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tmultiSort : false,\r\n");
      out.write("\t\t\turl: \"company/companyAction!findAllListChacked.action\",\r\n");
      out.write("\t\t\tqueryParams:queryParams,\r\n");
      out.write("\t\t\tcolumns : [[\r\n");
      out.write("\t\t\t            {field : 'ck',rowspan : 2,checkbox : true},\r\n");
      out.write("\t\t\t            {field : 'name',title : '单位名称',width : 80,rowspan : 2,align : 'center'},\r\n");
      out.write("\t\t\t            {field : 'tele',title : '单位电话',width : 100,rowspan : 2,align : 'center'},\r\n");
      out.write("\t\t\t            {field : 'corpNatureName',title : '单位性质',width : 140,rowspan:2,align : 'center'},\r\n");
      out.write("\t\t\t            {field : 'foundedTime',title : '成立时间',width : 100,rowspan : 2,align : 'center',formatter:function(value,row,index){\r\n");
      out.write("\t\t\t            \t if(null!=value){\r\n");
      out.write("\t\t\t            \t\t  var date = new Date(value);\r\n");
      out.write("\t\t\t            \t\t  return date.getFullYear() + '-' + (date.getMonth() + 1) + '-' + date.getDate();\r\n");
      out.write("\t\t\t            \t  }\r\n");
      out.write("\t\t\t            \t  return \" \";\r\n");
      out.write("\t\t\t             }},\r\n");
      out.write("\t\t\t            {field : 'regCapital',title : '注册资本',width : 80,rowspan : 2,align : 'center'},\r\n");
      out.write("\t\t\t            {field : 'areaSize',title : '营业面积',width : 80,rowspan : 2,align : 'center'},\r\n");
      out.write("\t\t\t            {field : 'empAmount',title : '员工数量',width : 80,rowspan : 2,align : 'center'},\r\n");
      out.write("\t\t\t            {title : '单地址位',width : 340,colspan : 4,align : 'center'}\r\n");
      out.write("\t\t            ],\r\n");
      out.write("\t\t\t\t\t[\r\n");
      out.write("\t\t\t\t\t\t{field : 'dwProvinceName',title : '省',width : 80,align : 'center'},\r\n");
      out.write("\t\t\t\t\t\t{field : 'dwCityName',title : '市',width : 80,align : 'center'},\r\n");
      out.write("\t\t\t\t\t\t{field : 'dwAreaName',title : '县/区',width : 80,align : 'center'},\r\n");
      out.write("\t\t\t\t\t\t{field : 'dwAddrDetails',title : '详细地址',width : 200,align : 'center'}\r\n");
      out.write("\t\t\t\t\t] ],\r\n");
      out.write("\t\t\ttoolbar : [ {\r\n");
      out.write("\t\t\t\ticonCls : 'icon-edit',\r\n");
      out.write("\t\t\t\ttext : '编辑',\r\n");
      out.write("\t\t\t\thandler : doEditDw\r\n");
      out.write("\t\t\t}, \"-\", {\r\n");
      out.write("\t\t\t\ticonCls : 'icon-cut',\r\n");
      out.write("\t\t\t\ttext : '删除',\r\n");
      out.write("\t\t\t\thandler : doDeleteDw\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\t\ttext : '保存',\r\n");
      out.write("\t\t\t\thandler : doSaveDw\r\n");
      out.write("\t\t\t} ],\r\n");
      out.write("\t\t\tonLoadSuccess : function(data) {\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < data.rows.length; i++) {\r\n");
      out.write("\t\t\t\t\tif (\"checked\" == data.rows[i].stateChecked) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#dwDatagrid\").datagrid(\"selectRow\",i);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//新增保存单位\r\n");
      out.write("function toSaveDw(){\r\n");
      out.write("\t//客户基本信息是否保存的标志\r\n");
      out.write("\tif(!checkIsSaveLoaner()) return false;\r\n");
      out.write("\tif(!$(\"#dwform\").form('validate')){return false;}\r\n");
      out.write("\t//贷款人客户id\r\n");
      out.write("\tvar $loanerId = $(\"#loanerId\").val();\r\n");
      out.write("\t//发送请求保存紧急联系人\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\tcache: true,\r\n");
      out.write("\t\ttype: \"POST\",\r\n");
      out.write("\t\turl:\"company/companyAction!saveCompany.action?loanerId=\"+$loanerId,\r\n");
      out.write("\t\tdata:$('#dwform').serialize(),\r\n");
      out.write("\t\tasync: false,\r\n");
      out.write("\t    error: function(request) {\r\n");
      out.write("\t        alert(\"Connection error\");\r\n");
      out.write("\t    },\r\n");
      out.write("\t    success: function(result) {\r\n");
      out.write("\t\t\tif(result.status){\r\n");
      out.write("\t\t\t\t$(\"#dwDatagrid\").datagrid('reload',{loanerId:$loanerId});//刷新列表\r\n");
      out.write("\t\t\t\t$('#dwform').form('clear');//清空form表单\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tparent.$.messager.show({\r\n");
      out.write("\t\t\t\ttitle : result.title,\r\n");
      out.write("\t\t\t\tmsg : result.message,\r\n");
      out.write("\t\t\t\ttimeout : 4000 * 2\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("//保存订单与工作单位关系\r\n");
      out.write("function doSaveDw(){\r\n");
      out.write("\t//客户基本信息是否保存的标志\r\n");
      out.write("\tif(!checkIsSaveLoaner()) return false;\r\n");
      out.write("\t//订单id\r\n");
      out.write("\tvar $loanOrderId = $(\"#loanOrderId\").val();\r\n");
      out.write("\tvar row = $(\"#dwDatagrid\").datagrid(\"getSelected\");\r\n");
      out.write("\tvar rows = $('#dwDatagrid').datagrid('getSelections');\r\n");
      out.write("\tif (row == null) {\r\n");
      out.write("\t\t$.messager.alert(\"提示\", \"请至少勾选一条记录作为本次借款的工作单位!\", \"warning\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar ids = new Array();\r\n");
      out.write("\tfor(var i=0;i<rows.length;i++){\r\n");
      out.write("\t\tids.push(rows[i].comId);\r\n");
      out.write("\t}\r\n");
      out.write("\tids=ids.join(\",\"); \r\n");
      out.write("\t$.ajax( {\r\n");
      out.write("\t\ttype : \"POST\",\r\n");
      out.write("\t\turl : 'loanorderAndCompany/loanorderAndCompanyAction!saveLoanorderAndCompany.action',\r\n");
      out.write("\t\tdata: \"comIds=\"+ids+\"&loanOrderId=\"+$loanOrderId,\r\n");
      out.write("\t\tdataType:'json',\r\n");
      out.write("\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\tparent.$.messager.show({\r\n");
      out.write("\t\t\t\ttitle : result.title,\r\n");
      out.write("\t\t\t\tmsg : result.message,\r\n");
      out.write("\t\t\t\ttimeout : 4000 * 2\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("//编辑\r\n");
      out.write("function doEditDw(){\r\n");
      out.write("\t//客户基本信息是否保存的标志\r\n");
      out.write("\tif(!checkIsSaveLoaner()) return false;\r\n");
      out.write("\tvar row = $(\"#dwDatagrid\").datagrid(\"getSelected\");\r\n");
      out.write("\tvar rows = $('#dwDatagrid').datagrid('getSelections');\r\n");
      out.write("\tif (row == null) {\r\n");
      out.write("\t\t$.messager.alert(\"提示\", \"请选择一条记录进行编辑!\", \"warning\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(rows.length >1){\r\n");
      out.write("\t\t$.messager.alert(\"提示\", \"您只能选择一条记录执行编辑!\", \"warning\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t//获取订单id\r\n");
      out.write("\tvar $loanOrderId = $(\"#loanOrderId\").val();\r\n");
      out.write("\t$.ajax( {\r\n");
      out.write("\t\ttype : \"POST\",\r\n");
      out.write("\t\turl : 'company/companyAction!doEdit.action',\r\n");
      out.write("\t\tdata : \"comId=\"+row.comId+\"&loanOrderId=\"+$loanOrderId,\r\n");
      out.write("\t\tdataType:'JSON',\r\n");
      out.write("\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\tif(result.status){\r\n");
      out.write("\t\t\t\t$(\"#dwform\").form('load',row);\r\n");
      out.write("\t\t\t\t//渲染市区\r\n");
      out.write("\t\t\t\trenderProvinceSelect('dwProvince','dwCity','dwArea',row.dwProvince,row.dwCity,row.dwArea);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tparent.$.messager.show({\r\n");
      out.write("\t\t\t\t\ttitle : result.title,\r\n");
      out.write("\t\t\t\t\tmsg : result.message,\r\n");
      out.write("\t\t\t\t\ttimeout : 4000 * 2\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("//删除\r\n");
      out.write("function doDeleteDw(){\r\n");
      out.write("\t//客户基本信息是否保存的标志\r\n");
      out.write("\tif(!checkIsSaveLoaner()) return false;\r\n");
      out.write("\t//获取订单id\r\n");
      out.write("\tvar $loanOrderId = $(\"#loanOrderId\").val();\r\n");
      out.write("\tvar selected = $('#dwDatagrid').datagrid('getSelections');\r\n");
      out.write("\tif (selected.length <= 0) {\r\n");
      out.write("\t\t$.messager.alert(\"提示\", \"请至少选择一条记录执行删除!\", \"warning\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar ids = new Array();\r\n");
      out.write("\tfor(var i=0,len=selected.length; i<len; i++){\r\n");
      out.write("\t\tids.push(selected[i].comId);\r\n");
      out.write("\t}\r\n");
      out.write("\tids = ids.join(\",\");\r\n");
      out.write("\t$.messager.confirm('删除', '执行删除后，数据将不可恢复,是否执行?', function(d) {\r\n");
      out.write("\t\tif (d) {\r\n");
      out.write("\t\t\t$.ajax( {\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\turl : 'company/companyAction!doDeleteById.action',\r\n");
      out.write("\t\t\t\tdata : \"comIds=\"+ids+\"&loanOrderId=\"+$loanOrderId,\r\n");
      out.write("\t\t\t\tdataType:'JSON',\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tif(result.status){\r\n");
      out.write("\t\t\t\t\t\t//贷款人客户id\r\n");
      out.write("\t\t\t\t\t\tvar $loanerId = $(\"#loanerId\").val();\r\n");
      out.write("\t\t\t\t\t\t//刷新列表\r\n");
      out.write("\t\t\t\t\t\t$(\"#dwDatagrid\").datagrid(\"reload\",{loanerId:$loanerId});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tparent.$.messager.show({\r\n");
      out.write("\t\t\t\t\t\ttitle : result.title,\r\n");
      out.write("\t\t\t\t\t\tmsg : result.message,\r\n");
      out.write("\t\t\t\t\t\ttimeout : 4000 * 2\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\n");
      out.write("</script>\r\n");
      out.write("<div class=\"well well-small\" >\r\n");
      out.write("\t  <form id=\"dwform\">\r\n");
      out.write("\t    <input name=\"comId\" type=\"hidden\"/><!-- 公司id -->\r\n");
      out.write("\t    <input name=\"creator\" type=\"hidden\"/><!-- 创建人 -->\r\n");
      out.write("\t    <input name=\"createDate\" type=\"hidden\"/><!-- 创建时间 -->\r\n");
      out.write("\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>工作单位:</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"name\" class=\"easyui-textbox easyui-validatebox\" data-options=\"required:true,validType:'length[0,16]'\" type=\"text\" />\r\n");
      out.write("\t\t\t\t<th>单位电话:</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"tele\" type=\"text\" class=\"easyui-textbox easyui-validatebox\" data-options=\"required:true,validType:'phone'\"/></td>\r\n");
      out.write("\t\t\t\t<th>注册号:</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"regId\" type=\"text\" class=\"easyui-textbox easyui-validatebox\" data-options=\"required:true\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>营业面积(m²):</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"areaSize\" type=\"text\" class=\"easyui-textbox easyui-validatebox\" data-options=\"required:true,validType:['integer','length[0,10]']\"/></td>\r\n");
      out.write("\t\t\t\t<th>注册资本(元):</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"regCapital\" type=\"text\" class=\"easyui-textbox easyui-validatebox\" data-options=\"required:true,validType:'mDouble'\"/></td>\r\n");
      out.write("\t\t\t\t<th>成立时间:</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"foundedTime\" type=\"text\" class=\"easyui-datebox\"  editable='false'/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>单位性质:</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"corpNature\" type=\"text\" class=\"easyui-textbox\"/></td>\r\n");
      out.write("\t\t\t\t<th>员工数量:</th>\r\n");
      out.write("\t\t\t\t<td><input name=\"empAmount\" type=\"text\" class=\"easyui-textbox easyui-validatebox\" data-options=\"required:true,validType:'integer'\"/></td>\r\n");
      out.write("\t\t\t\t<th>经营范围:</th>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\"><input name=\"businessScope\" type=\"text\" class=\"easyui-textbox easyui-validatebox\" data-options=\"required:true,validType:'length[0,100]'\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t    <th>单位地址:</th>\r\n");
      out.write("\t\t\t    <td colspan=\"5\">\r\n");
      out.write("\t\t\t                        省:<input id=\"dwProvince\" name=\"dwProvince\" class=\"easyui-combobox\" style=\"width: 100px;\" /> \r\n");
      out.write("\t\t\t\t\t市:<input id=\"dwCity\" name=\"dwCity\" class=\"easyui-combobox\" style=\"width: 100px;\"/> \r\n");
      out.write("\t\t\t\t\t县:<input id=\"dwArea\" name=\"dwArea\" class=\"easyui-combobox\" style=\"width: 100px;\"/>\r\n");
      out.write("\t\t\t\t\t详细地址:<input name=\"dwAddrDetails\" class=\"easyui-textbox easyui-validatebox\" data-options=\"required:true\" style=\"width: 300px;\"/>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t    <td colspan=\"6\" style=\"text-align: right;\">\r\n");
      out.write("\t\t\t       <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-reload\" onclick=\"$('#dwform').form('clear');\">重置</a>\r\n");
      out.write("\t\t\t       <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-save\" onclick=\"toSaveDw();\">保存</a>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<div >\r\n");
      out.write("  <table id=\"dwDatagrid\"></table>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
