/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2015-09-22 07:03:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fordertabel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/workspaces/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/JXC/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1427683825107L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

response.setHeader("Cache-Control","no-store");
response.setHeader("Pragrma","no-cache");
response.setDateHeader("Expires",0);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta HTTP-EQUIV=\"pragma\" CONTENT=\"no-cache\">\r\n");
      out.write("\t<meta HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache, must-revalidate\">\r\n");
      out.write("\t<meta HTTP-EQUIV=\"expires\" CONTENT=\"0\">\r\n");
      out.write("\t<title>登陆首页</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../media/css/easyui.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../media/css/icon.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../media/css/demo.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../media/js/WdatePicker.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../media/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../media/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t.indiv input{\r\n");
      out.write("\t\t\tborder: 1px solid #95b8e7;\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\theight: 20px;\r\n");
      out.write("\t\t\t/* background-color:#B0C4DE; */\r\n");
      out.write("\t\t\tfont-size:16px;\r\n");
      out.write("\t\t\tbackground-color:#F0F8FF;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ttd span{\r\n");
      out.write("\t\t\tfont-size: 16px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#screens td{\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\tfont-size: 16px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#screens td input{\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.datagrid-view{\r\n");
      out.write("\t\t\tbackground-color: #F8F8FF;\r\n");
      out.write("\t\t\tfont-size: 16px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.searchinput{\r\n");
      out.write("\t\t\tborder: 1px solid #95b8e7;border-radius: 5px;height:20px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<script >\r\n");
      out.write("\t\t  $(function(){\r\n");
      out.write("\t\t\t\t var today = Date.parse(new Date());\r\n");
      out.write("\t\t\t\t var diffday = 30*24*60*60*1000;\r\n");
      out.write("\t\t\t\t var begin = today-diffday;\r\n");
      out.write("\t\t\t\t var begindate = new Date(begin).pattern(\"yyyy-MM-dd\");\r\n");
      out.write("\t\t\t\t $(\"#begindate\").val(begindate);\r\n");
      out.write("\t\t\t\t $(\"#enddate\").val(new Date().pattern(\"yyyy-MM-dd\"));\r\n");
      out.write("\t\t\t\t var begindate = $('#begindate').val();\r\n");
      out.write("\t\t\t\t var enddate = $('#enddate').val();\r\n");
      out.write("\t\t\t\t $('#dg').datagrid({\r\n");
      out.write("\t\t\t\t\turl:\"getOrderByTime?begintime=\"+begindate+\"&endtime=\"+enddate\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t var pager = $('#dg').datagrid().datagrid('getPager'); // get the pager of datagrid\r\n");
      out.write("\t\t\t\t $(pager).pagination({  \r\n");
      out.write("\t\t\t\t\t \tbeforePageText: '第',//页数文本框前显示的汉字  \r\n");
      out.write("\t\t\t\t        afterPageText: '页    共 {pages} 页',  \r\n");
      out.write("\t\t\t\t        displayMsg: '当前显示 {from} - {to} 条记录   共 {total} 条记录',  \r\n");
      out.write("\t\t\t\t    });  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t});  \r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t/**   \r\n");
      out.write("\t* 扩展两个方法   \r\n");
      out.write("\t*/\r\n");
      out.write("\t$.extend($.fn.datagrid.methods, {\r\n");
      out.write("\t    /** \r\n");
      out.write("\t    * 开打提示功能   \r\n");
      out.write("\t    * @param {} jq   \r\n");
      out.write("\t    * @param {} params 提示消息框的样式   \r\n");
      out.write("\t    * @return {}   \r\n");
      out.write("\t    */\r\n");
      out.write("\t    doCellTip: function (jq, params) {\r\n");
      out.write("\t        function showTip(data, td, e) {\r\n");
      out.write("\t            if ($(td).text() == \"\")\r\n");
      out.write("\t                return;\r\n");
      out.write("\t            data.tooltip.text($(td).text()).css({\r\n");
      out.write("\t                top: (e.pageY + 10) + 'px',\r\n");
      out.write("\t                left: (e.pageX + 20) + 'px',\r\n");
      out.write("\t                'z-index': $.fn.window.defaults.zIndex,\r\n");
      out.write("\t                display: 'block'\r\n");
      out.write("\t            });\r\n");
      out.write("\t        };\r\n");
      out.write("\t        return jq.each(function () {\r\n");
      out.write("\t            var grid = $(this);\r\n");
      out.write("\t            var options = $(this).data('datagrid');\r\n");
      out.write("\t            if (!options.tooltip) {\r\n");
      out.write("\t                var panel = grid.datagrid('getPanel').panel('panel');\r\n");
      out.write("\t                var defaultCls = {\r\n");
      out.write("\t                    'border': '1px solid #333',\r\n");
      out.write("\t                    'padding': '1px',\r\n");
      out.write("\t                    'color': '#333',\r\n");
      out.write("\t                    'background': '#f7f5d1',\r\n");
      out.write("\t                    'position': 'absolute',\r\n");
      out.write("\t                    'max-width': '200px',\r\n");
      out.write("\t                    'border-radius': '4px',\r\n");
      out.write("\t                    '-moz-border-radius': '4px',\r\n");
      out.write("\t                    '-webkit-border-radius': '4px',\r\n");
      out.write("\t                    'display': 'none'\r\n");
      out.write("\t                }\r\n");
      out.write("\t                var tooltip = $(\"<div id='celltip'></div>\").appendTo('body');\r\n");
      out.write("\t                tooltip.css($.extend({}, defaultCls, params.cls));\r\n");
      out.write("\t                options.tooltip = tooltip;\r\n");
      out.write("\t                panel.find('.datagrid-body').each(function () {\r\n");
      out.write("\t                    var delegateEle = $(this).find('> div.datagrid-body-inner').length\r\n");
      out.write("\t                            ? $(this).find('> div.datagrid-body-inner')[0]\r\n");
      out.write("\t                            : this;\r\n");
      out.write("\t                    $(delegateEle).undelegate('td', 'mouseover').undelegate(\r\n");
      out.write("\t                            'td', 'mouseout').undelegate('td', 'mousemove')\r\n");
      out.write("\t                            .delegate('td', {\r\n");
      out.write("\t                                'mouseover': function (e) {\r\n");
      out.write("\t                                    if (params.delay) {\r\n");
      out.write("\t                                        if (options.tipDelayTime)\r\n");
      out.write("\t                                            clearTimeout(options.tipDelayTime);\r\n");
      out.write("\t                                        var that = this;\r\n");
      out.write("\t                                        options.tipDelayTime = setTimeout(\r\n");
      out.write("\t                                                function () {\r\n");
      out.write("\t                                                    showTip(options, that, e);\r\n");
      out.write("\t                                                }, params.delay);\r\n");
      out.write("\t                                    } else {\r\n");
      out.write("\t                                        showTip(options, this, e);\r\n");
      out.write("\t                                    }\r\n");
      out.write("\r\n");
      out.write("\t                                },\r\n");
      out.write("\t                                'mouseout': function (e) {\r\n");
      out.write("\t                                    if (options.tipDelayTime)\r\n");
      out.write("\t                                        clearTimeout(options.tipDelayTime);\r\n");
      out.write("\t                                    options.tooltip.css({\r\n");
      out.write("\t                                        'display': 'none'\r\n");
      out.write("\t                                    });\r\n");
      out.write("\t                                },\r\n");
      out.write("\t                                'mousemove': function (e) {\r\n");
      out.write("\t                                    var that = this;\r\n");
      out.write("\t                                    if (options.tipDelayTime) {\r\n");
      out.write("\t                                        clearTimeout(options.tipDelayTime);\r\n");
      out.write("\t                                        options.tipDelayTime = setTimeout(\r\n");
      out.write("\t                                                function () {\r\n");
      out.write("\t                                                    showTip(options, that, e);\r\n");
      out.write("\t                                                }, params.delay);\r\n");
      out.write("\t                                    } else {\r\n");
      out.write("\t                                        showTip(options, that, e);\r\n");
      out.write("\t                                    }\r\n");
      out.write("\t                                }\r\n");
      out.write("\t                            });\r\n");
      out.write("\t                });\r\n");
      out.write("\r\n");
      out.write("\t            }\r\n");
      out.write("\r\n");
      out.write("\t        });\r\n");
      out.write("\t    },\r\n");
      out.write("\t    /** \r\n");
      out.write("\t    * 关闭消息提示功能   \r\n");
      out.write("\t    * @param {} jq   \r\n");
      out.write("\t    * @return {}   \r\n");
      out.write("\t    */\r\n");
      out.write("\t    cancelCellTip: function (jq) {\r\n");
      out.write("\t        return jq.each(function () {\r\n");
      out.write("\t            var data = $(this).data('datagrid');\r\n");
      out.write("\t            if (data.tooltip) {\r\n");
      out.write("\t                data.tooltip.remove();\r\n");
      out.write("\t                data.tooltip = null;\r\n");
      out.write("\t                var panel = $(this).datagrid('getPanel').panel('panel');\r\n");
      out.write("\t                panel.find('.datagrid-body').undelegate('td',\r\n");
      out.write("\t                                'mouseover').undelegate('td', 'mouseout')\r\n");
      out.write("\t                                .undelegate('td', 'mousemove')\r\n");
      out.write("\t            }\r\n");
      out.write("\t            if (data.tipDelayTime) {\r\n");
      out.write("\t                clearTimeout(data.tipDelayTime);\r\n");
      out.write("\t                data.tipDelayTime = null;\r\n");
      out.write("\t            }\r\n");
      out.write("\t        });\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div data-options=\"region:'center',title:'订单管理'\">\r\n");
      out.write("\t\t<div style=\"background-color:#F8F8FF;align:center;width: 100%;height: 60px;overflow: hidden;\">\r\n");
      out.write("\t\t\t\t\t<form  style=\"margin-left: 1%;text-align: right;margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t<table style=\"float: right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>柜台</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"counterid\" class=\"searchstyle\" name=\"counterid\" style=\"border: 1px solid #95b8e7;border-radius: 5px;height: 24px;width: 140px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\" selected=\"selected\">全部</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>　国家</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"d_countrys\" style=\"border: 1px solid #95b8e7;border-radius: 5px;height: 24px;width: 140px;\" name=\"d_countrys\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\" selected=\"selected\">全部</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>　设备类型</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"equipment_type\" class=\"searchstyle\" name=\"equipment_type\" style=\"border: 1px solid #95b8e7;border-radius: 5px;height: 24px;width: 140px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\" selected=\"selected\">全部</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"0001\" >内部设备</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"0002\">外部设备</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>　日期:</td><td><input id=\"begindate\" name=\"begindate\" value=\"\" style=\"border: 1px solid #95b8e7;border-radius: 5px;\" class=\"Wdate\" type=\"text\" onFocus=\"WdatePicker({doubleCalendar:true,dateFmt:'yyyy-MM-dd',maxDate:'#F{$dp.$D(\\'enddate\\')}'})\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>--</td><td><input id=\"enddate\" name=\"enddate\" value=\"\" style=\"border: 1px solid #95b8e7;border-radius: 5px;\" class=\"Wdate\" type=\"text\" onFocus=\"WdatePicker({doubleCalendar:true,dateFmt:'yyyy-MM-dd',minDate:'#F{$dp.$D(\\'begindate\\')}'})\"/> </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a onclick=\"exportform();\" href=\"exportform\" class=\"easyui-linkbutton\" style=\"margin-right: 5px;width: 80px;height: 25px;\">导出报表</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a onclick=\"submits();\" class=\"easyui-linkbutton\" style=\"margin-right: 5px;width: 60px;height: 25px;\">查询</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <td><a href=\"exportform\" class=\"easyui-linkbutton\" style=\"margin-right: 2%;width: 80px;height: 25px;\">导出报表</a></td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t<!-- 表单开始 -->\r\n");
      out.write("\t\t\t\t<table id=\"dg\" style=\"overflow: auto;height: 90%;\" \r\n");
      out.write("\t\t\t\tdata-options=\"rownumbers:true,pagination:false,singleSelect:true,method:'get', remoteSort:false,multiSort:false, showFooter: true\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'ck',checkbox:true\"></th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'order_num',width:200,align:'center'\">订单号</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'rent_begindate',width:200,align:'center',sortable:true\">日期</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'counterid',width:140,align:'center'\">柜台</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'d_country',width:80,align:'center'\">国家</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'rent_day',width:80,align:'center'\">日租金</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'actuallday',width:80,align:'center'\">使用天数</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'acutallchargeday',width:80,align:'center'\">实际收费天数</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'cost_discount',width:80,align:'center'\">优惠金额</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'cost_sum',width:80,align:'center'\">实际收入</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'equipment_no',width:80,align:'center'\">设备类型</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'payment',width:80,align:'center'\">支付方式</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'modify_user',width:80,align:'center'\">制单人</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'remark',width:200,align:'center'\">备注</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t<!-- 表单结束 -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t <script type=\"text/javascript\">\r\n");
      out.write("\t \t$(function(){\r\n");
      out.write("\t \t\t $('#dg').datagrid({\r\n");
      out.write("\t \t        onLoadSuccess: function (data) {\r\n");
      out.write("\t \t            $('#dg').datagrid('doCellTip', {\r\n");
      out.write("\t \t                onlyShowInterrupt: true,     //是否只有在文字被截断时才显示tip，默认值为false            \r\n");
      out.write("\t \t                position: 'bottom',   //tip的位置，可以为top,botom,right,left\r\n");
      out.write("\t \t                cls: { 'background-color': '#D1EEEE' },  //tip的样式\r\n");
      out.write("\t \t                delay: 100   //tip 响应时间\r\n");
      out.write("\t \t            });\r\n");
      out.write("\t \t        }\r\n");
      out.write("\t \t    });\r\n");
      out.write("\t \t    $('.datagrid-header div').css('textAlign', 'center');   \r\n");
      out.write("\t \t});\r\n");
      out.write("\t \r\n");
      out.write("\t\tfunction submits(){\r\n");
      out.write("\t\t\tvar begindate = $('#begindate').val();\r\n");
      out.write("\t\t\tvar enddate = $('#enddate').val();\r\n");
      out.write("\t\t\tvar counterid = $(\"#counterid\").val();\r\n");
      out.write("\t\t\tvar equipment_type = $(\"#equipment_type\").val();\r\n");
      out.write("\t\t\tvar d_countrys = $(\"#d_countrys\").val();\r\n");
      out.write("\t\t\t $('#dg').datagrid({\r\n");
      out.write("\t\t\t\turl:\"getOrderByTime?begintime=\"+begindate+\"&endtime=\"+enddate+\"&counterid=\"+counterid+\"&d_countrys=\"+d_countrys+\"&equipment_type=\"+equipment_type,\r\n");
      out.write("\t\t\t });  \r\n");
      out.write("\t\t\t var pager = $('#dg').datagrid().datagrid('getPager'); // get the pager of datagrid\r\n");
      out.write("\t\t\t $(pager).pagination({  \r\n");
      out.write("\t\t\t\t \tbeforePageText: '第',//页数文本框前显示的汉字  \r\n");
      out.write("\t\t\t        afterPageText: '页    共 {pages} 页',  \r\n");
      out.write("\t\t\t        displayMsg: '当前显示 {from} - {to} 条记录   共 {total} 条记录',  \r\n");
      out.write("\t\t\t    }); \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t $('#dg').datagrid({\r\n");
      out.write("\t\t \t        onLoadSuccess: function (data) {\r\n");
      out.write("\t\t \t            $('#dg').datagrid('doCellTip', {\r\n");
      out.write("\t\t \t                onlyShowInterrupt: false,     //是否只有在文字被截断时才显示tip，默认值为false            \r\n");
      out.write("\t\t \t                position: 'bottom',   //tip的位置，可以为top,botom,right,left\r\n");
      out.write("\t\t \t                cls: { 'background-color': '#D1EEEE' },  //tip的样式\r\n");
      out.write("\t\t \t                delay: 100   //tip 响应时间\r\n");
      out.write("\t\t \t            });\r\n");
      out.write("\t\t \t        }\r\n");
      out.write("\t\t \t    });\r\n");
      out.write("\t\t \t    $('.datagrid-header div').css('textAlign', 'center');   \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction exportform(){\r\n");
      out.write("\t\t\tvar begindate = $('#begindate').val();\r\n");
      out.write("\t\t\tvar enddate = $('#enddate').val();\r\n");
      out.write("\t\t\tvar counterid = $(\"#counterid\").val();\r\n");
      out.write("\t\t\tvar equipment_type = $(\"#equipment_type\").val();\r\n");
      out.write("\t\t\tvar d_countrys = $(\"#d_countrys\").val();\r\n");
      out.write("\t\t\tif(begindate==\"\" || enddate == \"\"){\r\n");
      out.write("\t\t\t\talert(\"请选择日期!\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tjQuery.ajax({\r\n");
      out.write("\t\t\t\turl:'exportform',\r\n");
      out.write("\t\t\t\ttype:'post',\r\n");
      out.write("\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\tdata:{begindate:begindate,enddate:enddate,counterid:counterid,equipment_type:equipment_type,d_countrys:d_countrys},\r\n");
      out.write("\t\t\t\terror:function(){},\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tif(data==1){\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<script language=\"javascript\" type=\"text/javascript\">  \r\n");
      out.write("\t\t\t   /**     \r\n");
      out.write("\t\t\t\t * 对Date的扩展，将 Date 转化为指定格式的String     \r\n");
      out.write("\t\t\t\t * 月(M)、日(d)、12小时(h)、24小时(H)、分(m)、秒(s)、周(E)、季度(q) 可以用 1-2 个占位符     \r\n");
      out.write("\t\t\t\t * 年(y)可以用 1-4 个占位符，毫秒(S)只能用 1 个占位符(是 1-3 位的数字)     \r\n");
      out.write("\t\t\t\t * eg:     \r\n");
      out.write("\t\t\t\t * (new Date()).pattern(\"yyyy-MM-dd hh:mm:ss.S\") ==> 2006-07-02 08:09:04.423     \r\n");
      out.write("\t\t\t\t * (new Date()).pattern(\"yyyy-MM-dd E HH:mm:ss\") ==> 2009-03-10 二 20:09:04     \r\n");
      out.write("\t\t\t\t * (new Date()).pattern(\"yyyy-MM-dd EE hh:mm:ss\") ==> 2009-03-10 周二 08:09:04     \r\n");
      out.write("\t\t\t\t * (new Date()).pattern(\"yyyy-MM-dd EEE hh:mm:ss\") ==> 2009-03-10 星期二 08:09:04     \r\n");
      out.write("\t\t\t\t * (new Date()).pattern(\"yyyy-M-d h:m:s.S\") ==> 2006-7-2 8:9:4.18     \r\n");
      out.write("\t\t\t\t */       \r\n");
      out.write("\t\t\t\tDate.prototype.pattern=function(fmt) {        \r\n");
      out.write("\t\t\t\t    var o = {        \r\n");
      out.write("\t\t\t\t    \"M+\" : this.getMonth()+1, //月份        \r\n");
      out.write("\t\t\t\t    \"d+\" : this.getDate(), //日        \r\n");
      out.write("\t\t\t\t    \"h+\" : this.getHours()%12 == 0 ? 12 : this.getHours()%12, //小时        \r\n");
      out.write("\t\t\t\t    \"H+\" : this.getHours(), //小时        \r\n");
      out.write("\t\t\t\t    \"m+\" : this.getMinutes(), //分        \r\n");
      out.write("\t\t\t\t    \"s+\" : this.getSeconds(), //秒        \r\n");
      out.write("\t\t\t\t    \"q+\" : Math.floor((this.getMonth()+3)/3), //季度        \r\n");
      out.write("\t\t\t\t    \"S\" : this.getMilliseconds() //毫秒        \r\n");
      out.write("\t\t\t\t    };        \r\n");
      out.write("\t\t\t\t    var week = {        \r\n");
      out.write("\t\t\t\t    \"0\" : \"\\日\",        \r\n");
      out.write("\t\t\t\t    \"1\" : \"\\一\",        \r\n");
      out.write("\t\t\t\t    \"2\" : \"\\二\",        \r\n");
      out.write("\t\t\t\t    \"3\" : \"\\三\",        \r\n");
      out.write("\t\t\t\t    \"4\" : \"\\四\",        \r\n");
      out.write("\t\t\t\t    \"5\" : \"\\五\",        \r\n");
      out.write("\t\t\t\t    \"6\" : \"\\六\"       \r\n");
      out.write("\t\t\t\t    };        \r\n");
      out.write("\t\t\t\t    if(/(y+)/.test(fmt)){        \r\n");
      out.write("\t\t\t\t        fmt=fmt.replace(RegExp.$1, (this.getFullYear()+\"\").substr(4 - RegExp.$1.length));        \r\n");
      out.write("\t\t\t\t    }        \r\n");
      out.write("\t\t\t\t    if(/(E+)/.test(fmt)){        \r\n");
      out.write("\t\t\t\t        fmt=fmt.replace(RegExp.$1, ((RegExp.$1.length>1) ? (RegExp.$1.length>2 ? \"\\星\\期\" : \"\\周\") : \"\")+week[this.getDay()+\"\"]);        \r\n");
      out.write("\t\t\t\t    }        \r\n");
      out.write("\t\t\t\t    for(var k in o){        \r\n");
      out.write("\t\t\t\t        if(new RegExp(\"(\"+ k +\")\").test(fmt)){        \r\n");
      out.write("\t\t\t\t            fmt = fmt.replace(RegExp.$1, (RegExp.$1.length==1) ? (o[k]) : ((\"00\"+ o[k]).substr((\"\"+ o[k]).length)));        \r\n");
      out.write("\t\t\t\t        }        \r\n");
      out.write("\t\t\t\t    }        \r\n");
      out.write("\t\t\t\t    return fmt;        \r\n");
      out.write("\t\t\t\t}      \r\n");
      out.write("</script>  \r\n");
      out.write("</body>\r\n");
      out.write(" \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/pages/user/user_ordertabel.jsp(198,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${counterlist!=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/pages/user/user_ordertabel.jsp(199,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/user/user_ordertabel.jsp(199,10) '${counterlist }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${counterlist }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/pages/user/user_ordertabel.jsp(199,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("counterlists");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${counterlists.counter_code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${counterlists.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/pages/user/user_ordertabel.jsp(209,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${country!=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /WEB-INF/pages/user/user_ordertabel.jsp(210,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/user/user_ordertabel.jsp(210,10) '${country }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${country }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/pages/user/user_ordertabel.jsp(210,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("countrys");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countrys.ITEM_VALUE }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countrys.ITEM_TEXT }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
