/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-09-18 03:06:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.loanOrder;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class auditInfoRecordDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
	String loanOrderId = request.getParameter("loanOrderId");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"  \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("<title>稽核信息详情</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../layout/script.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\ttable {\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tborder-left: 1px solid black;border-top: 1px solid black;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable td{\r\n");
      out.write("\t\tborder-right: 1px solid black; border-bottom: 1px solid black;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable th{\r\n");
      out.write("\t\tborder-right: 1px solid black; border-bottom: 1px solid black;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\tvar tableStr = \"\";\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"auditInfoRecord/auditInfoRecordAction!findAuditInfoDetailByOid.action\",\r\n");
      out.write("\t\t\t\tdata:{\"loanOrderId\":'");
      out.print(request.getParameter("loanOrderId"));
      out.write("'},\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tconsole.info(data);\r\n");
      out.write("\t\t\t\t\tif(data){\r\n");
      out.write("\t\t\t\t\t\ttableStr += \"<tr><th style='width:100px;'>姓名</th><th style='width:120px;'>联系方式</th><th style='width:140px;'>稽核对象</th><th style='width:260px;'>电核</th><th style='width:260px;'>网核</th><th style='width:100px;'>操作</th></tr>\";\r\n");
      out.write("\t\t\t\t\t\t$.each(data,function(i,item){\r\n");
      out.write("\t\t\t\t\t\t\ttableStr += \"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\ttableStr += \"<td>\"+item.name+\"</td><td>\"+item.contactMethod+\"</td><td>\"+item.auditItemName+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\ttableStr += \"<td>\"+item.phoneAuditRecord+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\ttableStr += \"<td>\"+item.webAuditRecord+\"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\ttableStr += \"<td><a href='javascript:void(0);' onclick=\\\"checkAttachment('\"+item.auditId+\"')\\\">查看附件</a></td>\";\r\n");
      out.write("\t\t\t\t\t\t\ttableStr += \"</tr>\"; \r\n");
      out.write("\t\t\t\t\t\t}); \r\n");
      out.write("\t\t\t\t\t\t$(tableStr).appendTo(\"#auditReportDetailTable\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#noMessage\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction checkAttachment(auditId){\r\n");
      out.write("\t\t\tvar loanOrderId = $(\"#loanOrderId\").val();\r\n");
      out.write("\t\t\tcheckAttachementDetail(auditId,loanOrderId,'','1');\r\n");
      out.write("\t\t\t/* $.ajax({\r\n");
      out.write("\t\t\t\turl:\"attachment/attachmentAction!findAttachmentByAuditId.action\",\r\n");
      out.write("\t\t\t\tdata:{\"auditId\":auditId},\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tconsole.info(data);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}); */\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div style=\"width:100%;height:100%;overflow:auto;text-align: center;\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"loanOrderId\" value=\"");
      out.print(loanOrderId);
      out.write("\">\r\n");
      out.write("\t\t<div id=\"noMessage\" style=\"width: 100%;height:300px;text-align: center;padding-top:250px;display: none;\">\r\n");
      out.write("\t\t\t<font size=\"6\" style=\"font-weight: bold;box-shadow: 3px 3px 5px 3px;\">\r\n");
      out.write("\t\t\t\t暂无稽核信息\r\n");
      out.write("\t\t\t</font>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table cellpadding=\"5px;\" id=\"auditReportDetailTable\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
