package com.oasys.model;

// Generated 2015-12-24 16:41:01 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;

/**
 * TEmUsers generated by hbm2java
 */
@Entity
@Table(name = "t_em_users",catalog="QQMS")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String userId;
	private String name;
	private Integer departmentId;
	private String office;
	private String mobile;
	private String phone;
	private String parent;
	private String orgName;


	public User() {
	}

	public User(String userId, String name, Integer departmentId,
			String office, String mobile, String phone) {
		this.userId = userId;
		this.name = name;
		this.departmentId = departmentId;
		this.office = office;
		this.mobile = mobile;
		this.phone = phone;
	}

	
	public User setUserFunc(String str,String value){
		switch (str) {
		case "userid":
			setUserId(value);
			break;
		case "name":
			setName(value);
			break;
		case "departmentid":
			setDepartmentId(Integer.valueOf(value));
			break;
		case "office":
			setOffice(value);
			break;
		case "mobile":
			setMobile(value);
			break;			
		case "phone":
			setPhone(value);
			break;	
		case "parent":
			setParent(value);
			break;
		default:
			break;
		}
		return this;
	} 
	
	public static List<User> parse(String protocolXML){
		List<User> userList = new ArrayList<User>();
		try {
			DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
			DocumentBuilder builder = factory.newDocumentBuilder();
			Document doc = builder.parse(new InputSource(new StringReader(
					protocolXML)));
			Element root = doc.getDocumentElement();
			NodeList books = root.getChildNodes();
			User user = new User();
			String value = "";
			if (books != null) {
				for (int i = 0; i < books.getLength(); i++) {
					Node book = books.item(i);
					NodeList nodeList = book.getChildNodes();
					user = new User();
					for (int j = 0; j < nodeList.getLength(); j++) {
						book = nodeList.item(j);
						value = book.getFirstChild() ==null ? "": book.getFirstChild().getNodeValue();
						user = user.setUserFunc(book.getNodeName(), value);
					}
					userList.add(user);
				}
			}
		} catch (Exception e) {
			// TODO: handle exception
		}
		return userList;
	}
	
	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "USER_ID", length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "PARENT", length = 50)
	public String getParent() {
		return parent;
	}

	public void setParent(String parent) {
		this.parent = parent;
	}
	
	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DEPARTMENT_ID")
	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "OFFICE", length = 50)
	public String getOffice() {
		return this.office;
	}

	public void setOffice(String office) {
		this.office = office;
	}

	@Column(name = "MOBILE", length = 50)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "PHONE", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	
	@Column(name="ORG_NAME",length = 100)
	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

}
