/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-12-28 01:43:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.investOrder;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class investOrderList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\tcreateInvestOrderGrid1();\r\n");
      out.write("\t$('#touzijine').numberbox({    \r\n");
      out.write("\t    min:0,    \r\n");
      out.write("\t    precision:2    \r\n");
      out.write("\t});  \r\n");
      out.write("});\r\n");
      out.write("function createInvestOrderGrid1(){\r\n");
      out.write("\tvar loanBgDate = $(\"#loanBgDate\").val();\r\n");
      out.write("\t$(\"#investOrderGrid1\").datagrid({\r\n");
      out.write("\t\turl:\"debtMatching/debtMatchingAction!findListByOrderStatus.action?loanBgDate=\"+loanBgDate+\"&investOrderIds=\"+investOrderIds,\r\n");
      out.write("\t\twidth: 'auto',\r\n");
      out.write("\t\theight: $(this).height()-270,\r\n");
      out.write("\t\tpagination:false,\r\n");
      out.write("\t\trownumbers:true,\r\n");
      out.write("\t\tborder:true,\r\n");
      out.write("\t\tsingleSelect:true,\r\n");
      out.write("\t\tnowrap:true,//如果为true，则在同一行中显示数据。设置为true可以提高加载性能。\r\n");
      out.write("\t\tpageSize:30,\r\n");
      out.write("\t\tpageList:[10,20,30,40],\r\n");
      out.write("\t\tremoteSort:false,//定义是否从服务器对数据进行排序。\r\n");
      out.write("\t\tstriped:true,//是否显示斑马线\r\n");
      out.write("\t\tcolumns:[[\r\n");
      out.write("\t\t        {field : 'investorName',title : '投资客户',width :100,align : 'center'},\r\n");
      out.write("                {field : 'idCrad',title : '身份证号',width : 180,align : 'center'},\r\n");
      out.write("\t            {field : 'prodName',title : '理财产品',width : 150,align : 'center'},\r\n");
      out.write("                {field : 'investEdu',title : '理财金额(元)',width : 100,align : 'center'},\r\n");
      out.write("                {field : 'usableEdu',title : '可用余额(元)',width : 150,align : 'center'},\r\n");
      out.write("                {field : 'endDate',title : '到期日期',width : 130,align : 'center'},\r\n");
      out.write("                {field : 'contractNo',title : '合同编号',width : 120,align : 'center',hidden:true},\r\n");
      out.write("                {field : 'caozuo',title : '操作',width : 100,align : 'center',formatter:function(value,row,index){\r\n");
      out.write("                \treturn \"<a href=\\\"javascript:void(0)\\\" onclick=\\\"touzi(\"+index+\");\\\">投资</a>&nbsp;&nbsp;\"+\"<a href=\\\"javascript:void(0)\\\" onclick=\\\"quanxuan(\"+index+\");\\\">全选</a>\";\r\n");
      out.write("                }}\r\n");
      out.write("\t   ]]\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("var rowdata;\r\n");
      out.write("/**\r\n");
      out.write(" * 弹出输入金额弹框\r\n");
      out.write(" */\r\n");
      out.write("function touzi(index){\r\n");
      out.write("\t$(\"#myFormId\").form(\"clear\");\r\n");
      out.write("\t$(\"#touzitankuang\").dialog(\"open\");\r\n");
      out.write("\tvar rows = $(\"#investOrderGrid1\").datagrid(\"getRows\");\r\n");
      out.write("\trowdata = rows[index];\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 输入金额确定\r\n");
      out.write(" */\r\n");
      out.write("function queding(){\r\n");
      out.write("\tvar touzijine = $(\"#touzijine\").val();\r\n");
      out.write("\tif(touzijine == null || touzijine == \"\"){\r\n");
      out.write("\t\t$.messager.alert(\"提示\",\"请输入投资金额!\",\"warning\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t//匹配金额\r\n");
      out.write("\trowdata['matchEdu'] = touzijine;\r\n");
      out.write("\t//可用余额\r\n");
      out.write("\tvar usableEdu = rowdata['usableEdu'];\r\n");
      out.write("\tif(parseFloat(usableEdu) < parseFloat(touzijine)){\r\n");
      out.write("\t\t$.messager.alert(\"提示\",\"投资金额必须小于可用余额!\",\"warning\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\trowdata['usableEdu'] = parseFloat(usableEdu) - parseFloat(touzijine);\r\n");
      out.write("\t//手动还是自动标志\r\n");
      out.write("\tvar sign = $(\"#sign\").val();\r\n");
      out.write("\tif(sign==\"zidong\"){\r\n");
      out.write("\t\ttoDeleteAll();\r\n");
      out.write("\t\t$(\"#sign\").val(\"shoudong\");\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#investOrderGrid\").datagrid(\"appendRow\",rowdata);\r\n");
      out.write("\t$(\"#touzitankuang\").dialog(\"close\");\r\n");
      out.write("\t$(\"#investOrderDialog\").dialog(\"close\");\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 搜索\r\n");
      out.write(" */\r\n");
      out.write("function toSearch(){\r\n");
      out.write("\t//投资客户\r\n");
      out.write("\tvar investorName = $(\"#investorName\").val();\r\n");
      out.write("\t//可用余额\r\n");
      out.write("\tvar usableEdu = $(\"#usableEdu\").val();\r\n");
      out.write("\t//到期日期\r\n");
      out.write("\tvar endDate01 = $(\"#endDate01\").datebox('getValue');\r\n");
      out.write("\tvar endDate02 = $(\"#endDate02\").datebox('getValue');\r\n");
      out.write("\tif(usableEdu==\"\"){\r\n");
      out.write("\t\t$(\"#investOrderGrid1\").datagrid(\"reload\",{\"investorAndInvestProductModel.investorName\":investorName,\"investorAndInvestProductModel.endDate01\":endDate01,\"investorAndInvestProductModel.endDate02\":endDate02});\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#investOrderGrid1\").datagrid(\"reload\",{\"investorAndInvestProductModel.investorName\":investorName,\"investorAndInvestProductModel.usableEdu\":usableEdu,\"investorAndInvestProductModel.endDate01\":endDate01,\"investorAndInvestProductModel.endDate02\":endDate02});\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 全选\r\n");
      out.write(" */\r\n");
      out.write("function quanxuan(index){\r\n");
      out.write("\tvar rows = $(\"#investOrderGrid1\").datagrid(\"getRows\");\r\n");
      out.write("\tvar data = rows[index];\r\n");
      out.write("\tdata['matchEdu'] = data['usableEdu'];\r\n");
      out.write("\tdata['usableEdu'] = 0;\r\n");
      out.write("\t$(\"#investOrderGrid\").datagrid(\"appendRow\",data);\r\n");
      out.write("\t$(\"#investOrderDialog\").dialog(\"close\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<div style=\"margin: 1px;\">\r\n");
      out.write("   <div class=\"well well-small\" style=\"margin-left: 5px; margin-top: 5px\">\r\n");
      out.write("\t<form id=\"searchForm\">\r\n");
      out.write("\t   <table>\r\n");
      out.write("\t     <tr>\r\n");
      out.write("\t       <td>投资客户:</td>\r\n");
      out.write("\t       <td><input id=\"investorName\" name=\"investorName\" class=\"easyui-textbox\" style=\"width: 120px;\"/></td>\r\n");
      out.write("\t       <td>可用余额:</td>\r\n");
      out.write("\t       <td><input id=\"usableEdu\" name=\"usableEdu\" class=\"easyui-textbox easyui-numberbox\" min=\"0\" precision=\"2\" style=\"width: 120px;\"/></td>\r\n");
      out.write("\t       <td>到期日期:</td>\r\n");
      out.write("\t       <td>\r\n");
      out.write("\t       <input id=\"endDate01\" name=\"endDate01\" class=\"easyui-textbox easyui-datebox\" editable=\"false\" style=\"width: 120px;\"/>\r\n");
      out.write("\t       -\r\n");
      out.write("\t       <input id=\"endDate02\" name=\"endDate02\" class=\"easyui-textbox easyui-datebox\" editable=\"false\" style=\"width: 120px;\"/>\r\n");
      out.write("\t       </td>\r\n");
      out.write("\t       <td>\r\n");
      out.write("\t         <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"toSearch();\">搜索</a>&nbsp;&nbsp;<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-reload\" onclick=\"$('#searchForm').form('clear')\">清空</a>\r\n");
      out.write("\t       </td>\r\n");
      out.write("\t     </tr>\r\n");
      out.write("\t   </table>\r\n");
      out.write("\t</form>\r\n");
      out.write("   </div>\r\n");
      out.write("   <table id=\"investOrderGrid1\"></table>\r\n");
      out.write("   <div id=\"touzitankuang\" class=\"easyui-dialog\" title=\"输入投资金额\" style=\"width:400px;height:200px;padding-top: 40px;padding-left: 35px;\" data-options=\"iconCls:'icon-save',closed: true,resizable:true,modal:true\">   \r\n");
      out.write("      <form id=\"myFormId\">\r\n");
      out.write("        <table>\r\n");
      out.write("\t         <tr>\r\n");
      out.write("\t            <th>请输入投资金额:</th>\r\n");
      out.write("\t            <td>\r\n");
      out.write("\t              <input id=\"touzijine\" name=\"touzijine\"/>\r\n");
      out.write("\t            </td>\r\n");
      out.write("\t         </tr> \r\n");
      out.write("\t         <tr>\r\n");
      out.write("\t           <td colspan=\"2\" align=\"right\">\r\n");
      out.write("\t              <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls='icon-ok' onclick=\"queding();\">确定</a>\r\n");
      out.write("\t              <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls='icon-cancel' onclick=\"$('#touzitankuang').dialog('close')\">取消</a>\r\n");
      out.write("\t           </td>\r\n");
      out.write("\t         </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
