/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-12-31 07:25:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.investApply;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class optionsList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>历史审批意见</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\tcreateOptionsGrid();\r\n");
      out.write("\t//是否显示查看附件\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"investApply/investApplyAction!isShowAttachment.action\",\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tdata:{\"taskId\":$taskId},\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tif(data){\r\n");
      out.write("\t\t\t\t$(\"#optionsGrid\").datagrid(\"hideColumn\",\"id\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("//审批意见列表\r\n");
      out.write(" function createOptionsGrid(){\r\n");
      out.write("\t$(\"#optionsGrid\").datagrid({\r\n");
      out.write("\t\turl : \"investOrderHis/investOrderHisAction!findAllInvestOrderHisList.action\",\r\n");
      out.write("\t\twidth : 'auto',\r\n");
      out.write("\t\theight : 463,\r\n");
      out.write("\t\tpagination:false,\r\n");
      out.write("\t\trownumbers:true,\r\n");
      out.write("\t\tborder:false,\r\n");
      out.write("\t\tsingleSelect:true,\r\n");
      out.write("\t\tnowrap:true,\r\n");
      out.write("\t\tqueryParams:{\"investOrderId\":row.investOrderId},\r\n");
      out.write("\t\tmultiSort:false,\r\n");
      out.write("\t\tcolumns : [ [ \r\n");
      out.write("\t\t              {field : 'agentTime',title : '受理时间',width : 120,sortable:true,align:'center'},\r\n");
      out.write("\t\t              {field : 'roleName',title : '受理角色',width : 120,align:'center'},\r\n");
      out.write("\t\t              {field : 'assigneeName',title : '受理人',width :100,align:'center'},\r\n");
      out.write("\t\t              {field : 'comment',title : '审批意见',width :300,align:'center'},\r\n");
      out.write("\t\t              {field : 'id',title : '查看附件',width :100,align:'center',formatter:function(value,row,index){\r\n");
      out.write("\t\t            \t\treturn \"<a href='javascript:void(0);' onclick='lookAttachment(\"+index+\");'>查看附件</a>\" ;\r\n");
      out.write("\t\t              }}\r\n");
      out.write("\t\t] ]\r\n");
      out.write("\t});\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("// 根据行索引获取行信息\r\n");
      out.write("function getRowData (index) {\r\n");
      out.write("    if (!$.isNumeric(index) || index < 0) { return undefined; }\r\n");
      out.write("    var rows = $(\"#optionsGrid\").datagrid(\"getRows\");\r\n");
      out.write("    return rows[index];\r\n");
      out.write("}\r\n");
      out.write("//查看附件信息\r\n");
      out.write("function lookAttachment(index){\r\n");
      out.write("\t\tvar row = getRowData(index);\r\n");
      out.write("\t\t$(\"#attachmentList\").dialog(\"open\");\r\n");
      out.write("\t\t$(\"#lookAttachmentList\").datagrid({\r\n");
      out.write("\t\t\turl : \"attachment/attachmentAction!findAllAttachmentList.action\",\r\n");
      out.write("\t\t\twidth : 'auto',\r\n");
      out.write("\t\t\theight : 430,\r\n");
      out.write("\t\t\tpagination:false,\r\n");
      out.write("\t\t\trownumbers:true,\r\n");
      out.write("\t\t\tborder:false,\r\n");
      out.write("\t\t\tsingleSelect:true,\r\n");
      out.write("\t\t\tnowrap:true,\r\n");
      out.write("\t\t\tqueryParams:{\"orderId\":row.investOrderId,\"userId\":row.assignee,\"orderType\":\"attachment_type_invest\"},\r\n");
      out.write("\t\t\tmultiSort:false,\r\n");
      out.write("\t\t\tcolumns : [ [ \r\n");
      out.write("\t\t\t              {field : 'attName',title : '附件名称',width : 200,sortable:true,align:'center'},\r\n");
      out.write("\t\t\t              {field : 'attTypeName',title : '附件类型',width : 160,align:'center'},\r\n");
      out.write("\t\t\t              {field : 'creatorName',title : '创建者',width : 170,align:'center'},\r\n");
      out.write("\t\t\t              {field : 'id',title : '查看附件',width :220,align:'center',formatter:function(value,row,index){\r\n");
      out.write("\t\t\t            \t\tvar result = \"<a target='_blank' href='jsp/openoffice/documentView.jsp?attId=\"+row.attId+\"'>在线预览</a>　　\" ;\r\n");
      out.write("\t\t\t            \t\t\tresult += \"<a target='_blank' href='javascript:void(0);' onclick=\\\"downloadAttachment4InvestOrder('\"+row.attId+\"');\\\">下载</a>　　\" ;\r\n");
      out.write("\t\t\t            \t\treturn result;\r\n");
      out.write("\t\t\t              }}\r\n");
      out.write("\t\t    ] ]\r\n");
      out.write("\t\t});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<table id=\"optionsGrid\"></table>\r\n");
      out.write("<div id=\"attachmentList\" class=\"easyui-dialog\" title=\"附件信息\" style=\"width:800px;height:500px;\" data-options=\"resizable:true,modal:true\" closed=\"true\">\r\n");
      out.write("\t<table id=\"lookAttachmentList\"></table>\r\n");
      out.write("</div>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
